// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BuscarCtaFact</b><br>
 * Generated     : <b>2016/01/12 09:26:56</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 12, 2016
 * @author Sandra
 */
public abstract class BuscarCtaFactHelper extends libreria.Accion
{
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasActivoPlanes() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasActivoPlanes"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasActivoPlanes(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasActivoPlanes"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasActivoServicio() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasActivoServicio"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasActivoServicio(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasActivoServicio"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPerfil() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPerfil"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPerfil(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPerfil"), anchor, flags);
	}
	
	/**
	 * SiebMenu: with default state.
	 *		ClassName : SiebMenu
	 * 		.class : SiebMenu
	 * 		RepositoryName : SiebMenu
	 */
	protected SiebMenuTestObject MenuSiebel() 
	{
		return new SiebMenuTestObject(
                        getMappedTestObject("MenuSiebel"));
	}
	/**
	 * SiebMenu: with specific test context and state.
	 *		ClassName : SiebMenu
	 * 		.class : SiebMenu
	 * 		RepositoryName : SiebMenu
	 */
	protected SiebMenuTestObject MenuSiebel(TestObject anchor, long flags) 
	{
		return new SiebMenuTestObject(
                        getMappedTestObject("MenuSiebel"), anchor, flags);
	}
	
	/**
	 * AccountNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Account Number
	 */
	protected SiebTextTestObject NroCtaFact() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroCtaFact"));
	}
	/**
	 * AccountNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Account Number
	 */
	protected SiebTextTestObject NroCtaFact(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroCtaFact"), anchor, flags);
	}
	
	/**
	 * NroServicio: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Serial Number
	 */
	protected SiebTextTestObject NroServicio() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroServicio"));
	}
	/**
	 * NroServicio: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Serial Number
	 */
	protected SiebTextTestObject NroServicio(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroServicio"), anchor, flags);
	}
	
	/**
	 * NewRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevoPerfil() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevoPerfil"));
	}
	/**
	 * NewRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevoPerfil(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevoPerfil"), anchor, flags);
	}
	
	/**
	 * MostrarMasMenos: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ToggleListRowCount
	 */
	protected SiebButtonTestObject button_toggleListRowCount() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_toggleListRowCount"));
	}
	/**
	 * MostrarMasMenos: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ToggleListRowCount
	 */
	protected SiebButtonTestObject button_toggleListRowCount(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_toggleListRowCount"), anchor, flags);
	}
	
	

	protected BuscarCtaFactHelper()
	{
		setScriptName("Scripts.Comun.BuscarCtaFact");
	}
	
}

