// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidacPostEnvio1</b><br>
 * Generated     : <b>2016/01/12 09:13:55</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 12, 2016
 * @author Sandra
 */
public abstract class ValidacPostEnvio1Helper extends libreria.Accion
{
	/**
	 * Status: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Status
	 */
	protected SiebPicklistTestObject EstadoPedidoVta() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoPedidoVta"));
	}
	/**
	 * Status: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Status
	 */
	protected SiebPicklistTestObject EstadoPedidoVta(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoPedidoVta"), anchor, flags);
	}
	
	/**
	 * BupdatePriceAll: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject VolveraValorar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("VolveraValorar"));
	}
	/**
	 * BupdatePriceAll: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject VolveraValorar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("VolveraValorar"), anchor, flags);
	}
	
	

	protected ValidacPostEnvio1Helper()
	{
		setScriptName("Scripts.Comun.ValidacPostEnvio1");
	}
	
}

