// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ASRM_Login</b><br>
 * Generated     : <b>2016/10/14 3:02:53 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  octubre 14, 2016
 * @author rft
 */
public abstract class ASRM_LoginHelper extends libreria.Accion
{
	/**
	 * Pagetablist: with default state.
	 *		.class : .Pagetablist
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Tabs() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Tabs"));
	}
	/**
	 * Pagetablist: with specific test context and state.
	 *		.class : .Pagetablist
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Tabs(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Tabs"), anchor, flags);
	}
	
	

	protected ASRM_LoginHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.ASRM_Login");
	}
	
}

