// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ASRM_ModificarEstadoSIM</b><br>
 * Generated     : <b>2017/02/09 6:18:57 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  febrero 09, 2017
 * @author rft
 */
public abstract class ASRM_ModificarEstadoSIMHelper extends libreria.Accion
{
	/**
	 * ActualizarInformación: with default state.
	 *		.text : Actualizar Información
	 * 		.class : TFrmActualizar_Datos
	 * 		.processName : Project_Actualizar_ASRM.exe
	 * 		.name : Actualizar Información
	 */
	protected TopLevelSubitemTestObject ActualizarWindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ActualizarWindow"));
	}
	/**
	 * ActualizarInformación: with specific test context and state.
	 *		.text : Actualizar Información
	 * 		.class : TFrmActualizar_Datos
	 * 		.processName : Project_Actualizar_ASRM.exe
	 * 		.name : Actualizar Información
	 */
	protected TopLevelSubitemTestObject ActualizarWindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ActualizarWindow"), anchor, flags);
	}
	
	/**
	 * Estado: with default state.
	 *		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Estado() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Estado"));
	}
	/**
	 * Estado: with specific test context and state.
	 *		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Estado(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Estado"), anchor, flags);
	}
	
	/**
	 * Information: with default state.
	 *		.text : Information
	 * 		.class : TMessageForm
	 * 		.processName : Project_Actualizar_ASRM.exe
	 * 		.name : Information
	 */
	protected TopLevelSubitemTestObject Informacion() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Informacion"));
	}
	/**
	 * Information: with specific test context and state.
	 *		.text : Information
	 * 		.class : TMessageForm
	 * 		.processName : Project_Actualizar_ASRM.exe
	 * 		.name : Information
	 */
	protected TopLevelSubitemTestObject Informacion(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Informacion"), anchor, flags);
	}
	
	/**
	 * ModificarEstadoDeTarjeta: with default state.
	 *		.text : Modificar Estado de Tarjeta
	 * 		.class : TGroupBox
	 * 		.name : Modificar Estado de Tarjeta
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject ModificarNumero() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("ModificarNumero"));
	}
	/**
	 * ModificarEstadoDeTarjeta: with specific test context and state.
	 *		.text : Modificar Estado de Tarjeta
	 * 		.class : TGroupBox
	 * 		.name : Modificar Estado de Tarjeta
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject ModificarNumero(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("ModificarNumero"), anchor, flags);
	}
	
	/**
	 * SIM: with default state.
	 *		.value : 89506010911111296188
	 * 		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject NroSIM() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("NroSIM"));
	}
	/**
	 * SIM: with specific test context and state.
	 *		.value : 89506010911111296188
	 * 		.class : .Text
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject NroSIM(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("NroSIM"), anchor, flags);
	}
	
	/**
	 * SIMConsultada: with default state.
	 *		.class : .Text
	 * 		.name : Tarjeta
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject NroSIMConsultado() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("NroSIMConsultado"));
	}
	/**
	 * SIMConsultada: with specific test context and state.
	 *		.class : .Text
	 * 		.name : Tarjeta
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject NroSIMConsultado(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("NroSIMConsultado"), anchor, flags);
	}
	
	/**
	 * Pagetablist: with default state.
	 *		.class : .Pagetablist
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Tabs() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Tabs"));
	}
	/**
	 * Pagetablist: with specific test context and state.
	 *		.class : .Pagetablist
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Tabs(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Tabs"), anchor, flags);
	}
	
	/**
	 * Maximize: with default state.
	 *		.text : Maximize
	 * 		.class : .Pushbutton
	 * 		.name : Maximize
	 * 		.classIndex : 1
	 */
	protected GuiTestObject maximizebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("maximizebutton"));
	}
	/**
	 * Maximize: with specific test context and state.
	 *		.text : Maximize
	 * 		.class : .Pushbutton
	 * 		.name : Maximize
	 * 		.classIndex : 1
	 */
	protected GuiTestObject maximizebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("maximizebutton"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okbutton"), anchor, flags);
	}
	
	/**
	 * Open: with default state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject openbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("openbutton"));
	}
	/**
	 * Open: with specific test context and state.
	 *		.text : Open
	 * 		.class : .Pushbutton
	 * 		.name : Open
	 * 		.classIndex : 0
	 */
	protected GuiTestObject openbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("openbutton"), anchor, flags);
	}
	
	

	protected ASRM_ModificarEstadoSIMHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.ASRM_ModificarEstadoSIM");
	}
	
}

