// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BRM_FavoritoValidarCambioNum</b><br>
 * Generated     : <b>2016/11/30 11:32:04</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  noviembre 30, 2016
 * @author Sandra
 */
public abstract class BRM_FavoritoValidarCambioNumHelper extends libreria.Accion
{
	/**
	 * NumFav: with default state.
	 *		componentCount : 1
	 * 		.class : com.portal.pfc.ui.table.PFCTable
	 * 		columnCount : 4
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject NumFav() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("NumFav"));
	}
	/**
	 * NumFav: with specific test context and state.
	 *		componentCount : 1
	 * 		.class : com.portal.pfc.ui.table.PFCTable
	 * 		columnCount : 4
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject NumFav(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("NumFav"), anchor, flags);
	}
	
	/**
	 * Pestañas: with default state.
	 *		tabCount : 11
	 * 		.class : com.portal.app.cc.comp.PAccountView
	 * 		.priorLabel : Nonpaying account
	 * 		accessibleContext.accessibleName : Promotion
	 * 		.tabs : RegularExpression(\{.*Summary.*\})
	 * 		name : RegularExpression(com\.portal\.bas\.PModelHandle.*, type=/account, hash=.*, mode ...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Pestañas() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * Pestañas: with specific test context and state.
	 *		tabCount : 11
	 * 		.class : com.portal.app.cc.comp.PAccountView
	 * 		.priorLabel : Nonpaying account
	 * 		accessibleContext.accessibleName : Promotion
	 * 		.tabs : RegularExpression(\{.*Summary.*\})
	 * 		name : RegularExpression(com\.portal\.bas\.PModelHandle.*, type=/account, hash=.*, mode ...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * ProdFav: with default state.
	 *		.itemCount : 1
	 * 		.itemText : {Numero Kolbi SMS Favorito}
	 * 		.class : javax.swing.JList
	 * 		.priorLabel : No Provisioning
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject ProdFav() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("ProdFav"));
	}
	/**
	 * ProdFav: with specific test context and state.
	 *		.itemCount : 1
	 * 		.itemText : {Numero Kolbi SMS Favorito}
	 * 		.class : javax.swing.JList
	 * 		.priorLabel : No Provisioning
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject ProdFav(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("ProdFav"), anchor, flags);
	}
	
	/**
	 * ServiceFav: with default state.
	 *		.itemCount : 4
	 * 		.itemText : {TELCO/GSM/SMS: <unknown935-20160913-135452-2-23852-1-facute01>,TELCO/GSM/TELEPH ...
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Service/ID:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject ServiceFav() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("ServiceFav"));
	}
	/**
	 * ServiceFav: with specific test context and state.
	 *		.itemCount : 4
	 * 		.itemText : {TELCO/GSM/SMS: <unknown935-20160913-135452-2-23852-1-facute01>,TELCO/GSM/TELEPH ...
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Service/ID:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject ServiceFav(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("ServiceFav"), anchor, flags);
	}
	
	/**
	 * CustomerCenter: with default state.
	 *		.captionText : Customer Center
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : Customer Center
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject customerCenter() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("customerCenter"));
	}
	/**
	 * CustomerCenter: with specific test context and state.
	 *		.captionText : Customer Center
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : Customer Center
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject customerCenter(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("customerCenter"), anchor, flags);
	}
	
	

	protected BRM_FavoritoValidarCambioNumHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.BRM_FavoritoValidarCambioNum");
	}
	
}

