// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CompraPlanCategoriaCatalogo</b><br>
 * Generated     : <b>2016/11/08 15:34:11</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  noviembre 08, 2016
 * @author Sandra
 */
public abstract class CompraPlanCategoriaCatalogoHelper extends libreria.Accion
{
	/**
	 * ButtonAddToCart0: with default state.
	 *		.text : Agregar ítem
	 * 		.href : javascript:void(0)
	 * 		.id : s_3_1_7_0_si
	 * 		OT : SiebWebnull
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : ButtonAddToCart.0
	 * 		.name : 
	 * 		UN : ButtonAddToCart.0
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AgregarItem0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("AgregarItem0"));
	}
	/**
	 * ButtonAddToCart0: with specific test context and state.
	 *		.text : Agregar ítem
	 * 		.href : javascript:void(0)
	 * 		.id : s_3_1_7_0_si
	 * 		OT : SiebWebnull
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : ButtonAddToCart.0
	 * 		.name : 
	 * 		UN : ButtonAddToCart.0
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AgregarItem0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("AgregarItem0"), anchor, flags);
	}
	
	/**
	 * ButtonAddToCart1: with default state.
	 *		.text : Agregar ítem
	 * 		.href : javascript:void(0)
	 * 		.id : s_3_1_7_1_si
	 * 		OT : SiebWebnull
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : ButtonAddToCart.1
	 * 		.name : 
	 * 		UN : ButtonAddToCart.1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AgregarItem1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("AgregarItem1"));
	}
	/**
	 * ButtonAddToCart1: with specific test context and state.
	 *		.text : Agregar ítem
	 * 		.href : javascript:void(0)
	 * 		.id : s_3_1_7_1_si
	 * 		OT : SiebWebnull
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : ButtonAddToCart.1
	 * 		.name : 
	 * 		UN : ButtonAddToCart.1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AgregarItem1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("AgregarItem1"), anchor, flags);
	}
	
	/**
	 * HtmlTable_1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject Categorias_T1() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Categorias_T1"));
	}
	/**
	 * HtmlTable_1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject Categorias_T1(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Categorias_T1"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Categorias_T2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Categorias_T2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Categorias_T2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Categorias_T2"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Categorias_T2_Ant() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Categorias_T2_Ant"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Categorias_T2_Ant(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Categorias_T2_Ant"), anchor, flags);
	}
	
	/**
	 * s_0_2_6_0: with default state.
	 *		.text : ICE Catalogo
	 * 		.id : s_0_2_6_0
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-R5JH"," ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject ICE_Catalogo() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ICE_Catalogo"));
	}
	/**
	 * s_0_2_6_0: with specific test context and state.
	 *		.text : ICE Catalogo
	 * 		.id : s_0_2_6_0
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-R5JH"," ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject ICE_Catalogo(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ICE_Catalogo"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject ListaProductos() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("ListaProductos"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject ListaProductos(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("ListaProductos"), anchor, flags);
	}
	
	/**
	 * NombreVisible0: with default state.
	 *		.text : Nueva Generación Kölbi
	 * 		.href : javascript:c_d(s_25,new Array("1-NVXWE5","s_1_2_10_0","SWERowId0=1-R5JF,SWERowId ...
	 * 		.id : s_1_2_10_0
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.0
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible0"));
	}
	/**
	 * NombreVisible0: with specific test context and state.
	 *		.text : Nueva Generación Kölbi
	 * 		.href : javascript:c_d(s_25,new Array("1-NVXWE5","s_1_2_10_0","SWERowId0=1-R5JF,SWERowId ...
	 * 		.id : s_1_2_10_0
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.0
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible0"), anchor, flags);
	}
	
	/**
	 * NombreVisible1: with default state.
	 *		.text : Terminales
	 * 		.href : javascript:c_d(s_25,new Array("1-R5JJ","s_1_2_10_1","SWERowId0=1-R5JF,SWERowId1= ...
	 * 		.id : s_1_2_10_1
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible1"));
	}
	/**
	 * NombreVisible1: with specific test context and state.
	 *		.text : Terminales
	 * 		.href : javascript:c_d(s_25,new Array("1-R5JJ","s_1_2_10_1","SWERowId0=1-R5JF,SWERowId1= ...
	 * 		.id : s_1_2_10_1
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible1"), anchor, flags);
	}
	
	/**
	 * NombreVisible2: with default state.
	 *		.text : Iphone
	 * 		.href : javascript:c_d(s_25,new Array("1-25A7A8","s_1_2_10_2","SWERowId0=1-R5JF,SWERowId ...
	 * 		.id : s_1_2_10_2
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.2
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible2"));
	}
	/**
	 * NombreVisible2: with specific test context and state.
	 *		.text : Iphone
	 * 		.href : javascript:c_d(s_25,new Array("1-25A7A8","s_1_2_10_2","SWERowId0=1-R5JF,SWERowId ...
	 * 		.id : s_1_2_10_2
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.2
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible2"), anchor, flags);
	}
	
	/**
	 * NombreVisible3: with default state.
	 *		.text : Kölbi
	 * 		.href : javascript:c_d(s_25,new Array("1-R5JI","s_1_2_10_3","SWERowId0=1-R5JF,SWERowId1= ...
	 * 		.id : s_1_2_10_3
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.3
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible3"));
	}
	/**
	 * NombreVisible3: with specific test context and state.
	 *		.text : Kölbi
	 * 		.href : javascript:c_d(s_25,new Array("1-R5JI","s_1_2_10_3","SWERowId0=1-R5JF,SWERowId1= ...
	 * 		.id : s_1_2_10_3
	 * 		OT : SiebWebLink
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order Catalog Product Catalog Category And Description List Applet.Display ...
	 * 		.name : 
	 * 		UN : Nombre visible.3
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NombreVisible3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("NombreVisible3"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Categoría: with default state.
	 *		.text : Categoría:ICE Catalogo
	 * 		.href : javascript:SWETargetGotoURL("/ecommunications_esn/start.swe?SWENeedContext=false ...
	 * 		.id : s_tb_1
	 * 		OT : SiebWebThreadbar
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order-Browse Catalog Category Details View - Category Only.1
	 * 		.name : 
	 * 		UN : Categoría
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_categoría() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_categoría"));
	}
	/**
	 * Categoría: with specific test context and state.
	 *		.text : Categoría:ICE Catalogo
	 * 		.href : javascript:SWETargetGotoURL("/ecommunications_esn/start.swe?SWENeedContext=false ...
	 * 		.id : s_tb_1
	 * 		OT : SiebWebThreadbar
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order-Browse Catalog Category Details View - Category Only.1
	 * 		.name : 
	 * 		UN : Categoría
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_categoría(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_categoría"), anchor, flags);
	}
	
	/**
	 * Catálogo: with default state.
	 *		.text : Catálogo:ICE Catálogo
	 * 		.href : javascript:SWETargetGotoURL("/ecommunications_esn/start.swe?SWENeedContext=false ...
	 * 		.id : s_tb_2
	 * 		OT : SiebWebThreadbar
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order-Browse Catalog View.2
	 * 		.name : 
	 * 		UN : Catálogo
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_catálogo() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_catálogo"));
	}
	/**
	 * Catálogo: with specific test context and state.
	 *		.text : Catálogo:ICE Catálogo
	 * 		.href : javascript:SWETargetGotoURL("/ecommunications_esn/start.swe?SWENeedContext=false ...
	 * 		.id : s_tb_2
	 * 		OT : SiebWebThreadbar
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Sales Order-Browse Catalog View.2
	 * 		.name : 
	 * 		UN : Catálogo
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_catálogo(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_catálogo"), anchor, flags);
	}
	
	/**
	 * s_3_2_17_2: with default state.
	 *		.text : PLAN CONVERSON 3 12 M
	 * 		.id : s_3_2_17_2
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-N200AG" ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	protected GuiTestObject link_s_3_2_17_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_3_2_17_2"));
	}
	/**
	 * s_3_2_17_2: with specific test context and state.
	 *		.text : PLAN CONVERSON 3 12 M
	 * 		.id : s_3_2_17_2
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-N200AG" ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	protected GuiTestObject link_s_3_2_17_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_3_2_17_2"), anchor, flags);
	}
	
	/**
	 * s_6_2_6_0: with default state.
	 *		.text : ALCATEL
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-S0M2ML" ...
	 * 		.id : s_6_2_6_0
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_s_6_2_6_0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_6_2_6_0"));
	}
	/**
	 * s_6_2_6_0: with specific test context and state.
	 *		.text : ALCATEL
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-S0M2ML" ...
	 * 		.id : s_6_2_6_0
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_s_6_2_6_0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_6_2_6_0"), anchor, flags);
	}
	
	/**
	 * s_6_2_6_8: with default state.
	 *		.text : SAMSUNG
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-S0M2N9" ...
	 * 		.id : s_6_2_6_8
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected GuiTestObject link_s_6_2_6_8() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_6_2_6_8"));
	}
	/**
	 * s_6_2_6_8: with specific test context and state.
	 *		.text : SAMSUNG
	 * 		.href : javascript:c_d(new Array("SWERowId","SWEField","SWERowIds"),new Array("1-S0M2N9" ...
	 * 		.id : s_6_2_6_8
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected GuiTestObject link_s_6_2_6_8(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_6_2_6_8"), anchor, flags);
	}
	
	

	protected CompraPlanCategoriaCatalogoHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.CompraPlanCategoriaCatalogo");
	}
	
}

