// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SIPV_ValidarRebajaIMEI</b><br>
 * Generated     : <b>2017/03/31 3:35:56 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  marzo 31, 2017
 * @author rft
 */
public abstract class SIPV_ValidarRebajaIMEIHelper extends libreria.Accion
{
	/**
	 * busqueda: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_btnConsultar
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : ctl00$ContentPlaceHolder1$btnConsultar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Busqueda() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Busqueda"));
	}
	/**
	 * busqueda: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_btnConsultar
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : ctl00$ContentPlaceHolder1$btnConsultar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Btn_Busqueda(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Btn_Busqueda"), anchor, flags);
	}
	
	/**
	 * busqueda: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_btnConsultar
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : ctl00$ContentPlaceHolder1$btnConsultar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Bton_Busqueda() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Bton_Busqueda"));
	}
	/**
	 * busqueda: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_btnConsultar
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : ctl00$ContentPlaceHolder1$btnConsultar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Bton_Busqueda(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Bton_Busqueda"), anchor, flags);
	}
	
	/**
	 * ConsultaIMEI: with default state.
	 *		.text : Consulta-IMEI
	 * 		.href : javascript:__doPostBack('ctl00$mnuPrincipal','Reportes\\Consulta-IMEI')
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ConsultaIMEI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ConsultaIMEI"));
	}
	/**
	 * ConsultaIMEI: with specific test context and state.
	 *		.text : Consulta-IMEI
	 * 		.href : javascript:__doPostBack('ctl00$mnuPrincipal','Reportes\\Consulta-IMEI')
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ConsultaIMEI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ConsultaIMEI"), anchor, flags);
	}
	
	/**
	 * IMEIEstado: with default state.
	 *		.text : IMEI-Estado
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_IMEI_Estado.aspx
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject EstadoIMEI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("EstadoIMEI"));
	}
	/**
	 * IMEIEstado: with specific test context and state.
	 *		.text : IMEI-Estado
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_IMEI_Estado.aspx
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject EstadoIMEI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("EstadoIMEI"), anchor, flags);
	}
	
	/**
	 * IEBrowserSIPV: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 * 		.documentName : RegularExpression(http://.*Sistema_Inventarios/App_Forms.*)
	 */
	protected BrowserTestObject IEBrowserSIPV() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("IEBrowserSIPV"));
	}
	/**
	 * IEBrowserSIPV: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 * 		.documentName : RegularExpression(http://.*Sistema_Inventarios/App_Forms.*)
	 */
	protected BrowserTestObject IEBrowserSIPV(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("IEBrowserSIPV"), anchor, flags);
	}
	
	/**
	 * IMEI: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_txtImei
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : ctl00$ContentPlaceHolder1$txtImei
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject IMEI() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("IMEI"));
	}
	/**
	 * IMEI: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_txtImei
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : ctl00$ContentPlaceHolder1$txtImei
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject IMEI(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("IMEI"), anchor, flags);
	}
	
	/**
	 * Reportes: with default state.
	 *		.text : Reportes
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_IMEI_Estado.aspx#
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Reportes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Reportes"));
	}
	/**
	 * Reportes: with specific test context and state.
	 *		.text : Reportes
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_IMEI_Estado.aspx#
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Reportes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Reportes"), anchor, flags);
	}
	
	/**
	 * TablaVenta: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_grdVenta
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TablaVenta() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TablaVenta"));
	}
	/**
	 * TablaVenta: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_grdVenta
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TablaVenta(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TablaVenta"), anchor, flags);
	}
	
	/**
	 * ConsultaIMEI: with default state.
	 *		.text : Consulta-IMEI
	 * 		.id : 
	 * 		.href : javascript:__doPostBack('ctl00$mnuPrincipal','Reportes\\Consulta-IMEI')
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_consultaIMEI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_consultaIMEI"));
	}
	/**
	 * ConsultaIMEI: with specific test context and state.
	 *		.text : Consulta-IMEI
	 * 		.id : 
	 * 		.href : javascript:__doPostBack('ctl00$mnuPrincipal','Reportes\\Consulta-IMEI')
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_consultaIMEI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_consultaIMEI"), anchor, flags);
	}
	
	/**
	 * IMEIEstado: with default state.
	 *		.text : IMEI-Estado
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_IMEI_Estado.aspx
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_imeiEstado() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_imeiEstado"));
	}
	/**
	 * IMEIEstado: with specific test context and state.
	 *		.text : IMEI-Estado
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_IMEI_Estado.aspx
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_imeiEstado(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_imeiEstado"), anchor, flags);
	}
	
	/**
	 * Reportes: with default state.
	 *		.text : Reportes
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_Ventas.aspx#
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_reportes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_reportes"));
	}
	/**
	 * Reportes: with specific test context and state.
	 *		.text : Reportes
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_Ventas.aspx#
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_reportes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_reportes"), anchor, flags);
	}
	
	

	protected SIPV_ValidarRebajaIMEIHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.SIPV_ValidarRebajaIMEI");
	}
	
}

