// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SIPV_ValidarCedula_Ant</b><br>
 * Generated     : <b>2017/03/28 15:59:02</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  marzo 28, 2017
 * @author Sandra
 */
public abstract class SIPV_ValidarCedula_AntHelper extends libreria.Accion
{
	/**
	 * Busqueda: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_imbConsulta
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : ctl00$ContentPlaceHolder1$imbConsulta
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Busqueda() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Busqueda"));
	}
	/**
	 * Busqueda: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_imbConsulta
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : ctl00$ContentPlaceHolder1$imbConsulta
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Busqueda(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Busqueda"), anchor, flags);
	}
	
	/**
	 * Cedula: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_txtCed
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : ctl00$ContentPlaceHolder1$txtCed
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject Cedula() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Cedula"));
	}
	/**
	 * Cedula: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_txtCed
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : ctl00$ContentPlaceHolder1$txtCed
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject Cedula(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Cedula"), anchor, flags);
	}
	
	/**
	 * ConsultaIMEI: with default state.
	 *		.text : Consulta IMEI
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_Ventas.aspx
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ConsultaIMEI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ConsultaIMEI"));
	}
	/**
	 * ConsultaIMEI: with specific test context and state.
	 *		.text : Consulta IMEI
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_Ventas.aspx
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ConsultaIMEI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ConsultaIMEI"), anchor, flags);
	}
	
	/**
	 * IMEI: with default state.
	 *		.id : ctl00_ContentPlaceHolder1_txtImei
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : ctl00$ContentPlaceHolder1$txtImei
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject IMEI() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("IMEI"));
	}
	/**
	 * IMEI: with specific test context and state.
	 *		.id : ctl00_ContentPlaceHolder1_txtImei
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : ctl00$ContentPlaceHolder1$txtImei
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject IMEI(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("IMEI"), anchor, flags);
	}
	
	/**
	 * MenuRebajos: with default state.
	 *		.text : Rebajos-Salidas
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_Ventas.aspx#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject MenuRebajos() 
	{
		return new GuiTestObject(
                        getMappedTestObject("MenuRebajos"));
	}
	/**
	 * MenuRebajos: with specific test context and state.
	 *		.text : Rebajos-Salidas
	 * 		.id : 
	 * 		.href : http://10.3.104.86/Sistema_Inventarios/App_Forms/wfConsulta_Ventas.aspx#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject MenuRebajos(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("MenuRebajos"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TablaIMEI() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TablaIMEI"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TablaIMEI(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TablaIMEI"), anchor, flags);
	}
	
	

	protected SIPV_ValidarCedula_AntHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.SIPV_ValidarCedula_Ant");
	}
	
}

