// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun.SistemasExternos;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>VEP_PagarRED</b><br>
 * Generated     : <b>2016/09/07 11:26:26</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  septiembre 07, 2016
 * @author Sandra
 */
public abstract class VEP_PagarREDHelper extends libreria.Accion
{
	/**
	 * Agregarsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Agregar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : agregar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonAgregar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonAgregar"));
	}
	/**
	 * Agregarsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Agregar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : agregar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonAgregar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonAgregar"), anchor, flags);
	}
	
	/**
	 * Consultarsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Consultar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : btnConsultar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultar"));
	}
	/**
	 * Consultarsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Consultar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : btnConsultar
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultar"), anchor, flags);
	}
	
	/**
	 * Imprimirbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Imprimir
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonImprimir() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonImprimir"));
	}
	/**
	 * Imprimirbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Imprimir
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonImprimir(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonImprimir"), anchor, flags);
	}
	
	/**
	 * Pagarsubmit: with default state.
	 *		.id : pagar
	 * 		.type : submit
	 * 		.value : Pagar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : _finish
	 * 		.classIndex : 1
	 */
	protected GuiTestObject BtonPagar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonPagar"));
	}
	/**
	 * Pagarsubmit: with specific test context and state.
	 *		.id : pagar
	 * 		.type : submit
	 * 		.value : Pagar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : _finish
	 * 		.classIndex : 1
	 */
	protected GuiTestObject BtonPagar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonPagar"), anchor, flags);
	}
	
	/**
	 * VerSeleccionados: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ver seleccionados
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : btnPagar
	 * 		.classIndex : 1
	 */
	protected GuiTestObject BtonVerSeleccionados() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonVerSeleccionados"));
	}
	/**
	 * VerSeleccionados: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ver seleccionados
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : btnPagar
	 * 		.classIndex : 1
	 */
	protected GuiTestObject BtonVerSeleccionados(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonVerSeleccionados"), anchor, flags);
	}
	
	/**
	 * Check: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : 1
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : recibosPen
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject Check() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("Check"));
	}
	/**
	 * Check: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : 1
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : recibosPen
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject Check(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("Check"), anchor, flags);
	}
	
	/**
	 * Mensajes: with default state.
	 *		.tag : TABLE
	 * 		.text : RegularExpression(*)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.contentText : RegularExpression(*)
	 * 		.classIndex : 2
	 */
	protected StatelessGuiSubitemTestObject Mensaje() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Mensaje"));
	}
	/**
	 * Mensajes: with specific test context and state.
	 *		.tag : TABLE
	 * 		.text : RegularExpression(*)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.contentText : RegularExpression(*)
	 * 		.classIndex : 2
	 */
	protected StatelessGuiSubitemTestObject Mensaje(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Mensaje"), anchor, flags);
	}
	
	/**
	 * MensajeREDNoEncontrado: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject MensajeREDNoEncontrado() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("MensajeREDNoEncontrado"));
	}
	/**
	 * MensajeREDNoEncontrado: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject MensajeREDNoEncontrado(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("MensajeREDNoEncontrado"), anchor, flags);
	}
	
	/**
	 * Menu_Apertura: with default state.
	 *		.id : oCMenu_Apertura
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Menu_Apertura() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Menu_Apertura"));
	}
	/**
	 * Menu_Apertura: with specific test context and state.
	 *		.id : oCMenu_Apertura
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Menu_Apertura(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Menu_Apertura"), anchor, flags);
	}
	
	/**
	 * oCMenu_Pagos: with default state.
	 *		.id : oCMenu_Pagos
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Menu_Pagos() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Menu_Pagos"));
	}
	/**
	 * oCMenu_Pagos: with specific test context and state.
	 *		.id : oCMenu_Pagos
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Menu_Pagos(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Menu_Pagos"), anchor, flags);
	}
	
	/**
	 * nroRED: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : nroRED
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject NroRED() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("NroRED"));
	}
	/**
	 * nroRED: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : nroRED
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject NroRED(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("NroRED"), anchor, flags);
	}
	
	/**
	 * OpcionCerrar_Caja: with default state.
	 *		.id : oCMenu_Cajas
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject OpcionCajaGral() 
	{
		return new GuiTestObject(
                        getMappedTestObject("OpcionCajaGral"));
	}
	/**
	 * OpcionCerrar_Caja: with specific test context and state.
	 *		.id : oCMenu_Cajas
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject OpcionCajaGral(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("OpcionCajaGral"), anchor, flags);
	}
	
	/**
	 * oCMenu_CajasUsuario: with default state.
	 *		.id : oCMenu_CajasUsuario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject OpcionCajero() 
	{
		return new GuiTestObject(
                        getMappedTestObject("OpcionCajero"));
	}
	/**
	 * oCMenu_CajasUsuario: with specific test context and state.
	 *		.id : oCMenu_CajasUsuario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject OpcionCajero(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("OpcionCajero"), anchor, flags);
	}
	
	/**
	 * Opcion2: with default state.
	 *		.id : oCMenu_Notas
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject OpcionMenu_Cobrar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("OpcionMenu_Cobrar"));
	}
	/**
	 * Opcion2: with specific test context and state.
	 *		.id : oCMenu_Notas
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject OpcionMenu_Cobrar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("OpcionMenu_Cobrar"), anchor, flags);
	}
	
	/**
	 * screen0: with default state.
	 *		.id : screen0
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 2
	 */
	protected StatelessGuiSubitemTestObject RED() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("RED"));
	}
	/**
	 * screen0: with specific test context and state.
	 *		.id : screen0
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 2
	 */
	protected StatelessGuiSubitemTestObject RED(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("RED"), anchor, flags);
	}
	
	/**
	 * TablaREDs: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TablaREDs() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TablaREDs"));
	}
	/**
	 * TablaREDs: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TablaREDs(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TablaREDs"), anchor, flags);
	}
	
	

	protected VEP_PagarREDHelper()
	{
		setScriptName("Scripts.Comun.SistemasExternos.VEP_PagarRED");
	}
	
}

