// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>AdministrarFacilidadesCM</b><br>
 * Generated     : <b>2016/04/20 18:24:20</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 20, 2016
 * @author Sandra
 */
public abstract class AdministrarFacilidadesCMHelper extends libreria.Accion
{
	/**
	 * AppletFacilidadesCM: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE Product Facilities Task List Applet
	 */
	protected SiebAppletTestObject AppletFacilidadesCM() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletFacilidadesCM"));
	}
	/**
	 * AppletFacilidadesCM: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE Product Facilities Task List Applet
	 */
	protected SiebAppletTestObject AppletFacilidadesCM(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletFacilidadesCM"), anchor, flags);
	}
	
	/**
	 * FacilidadesCM: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaFacilidadesCM() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaFacilidadesCM"));
	}
	/**
	 * FacilidadesCM: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaFacilidadesCM(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaFacilidadesCM"), anchor, flags);
	}
	
	/**
	 * NombreFacilidad: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Name
	 */
	protected SiebTextTestObject NombreFacilidad() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreFacilidad"));
	}
	/**
	 * NombreFacilidad: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Name
	 */
	protected SiebTextTestObject NombreFacilidad(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreFacilidad"), anchor, flags);
	}
	
	/**
	 * Seleccionado: with default state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : ICE Facilidades Flg
	 */
	protected SiebCheckboxTestObject Seleccionado() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Seleccionado"));
	}
	/**
	 * Seleccionado: with specific test context and state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : ICE Facilidades Flg
	 */
	protected SiebCheckboxTestObject Seleccionado(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Seleccionado"), anchor, flags);
	}
	
	/**
	 * Siguiente: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ButtonNext
	 */
	protected SiebButtonTestObject Siguiente() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Siguiente"));
	}
	/**
	 * Siguiente: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ButtonNext
	 */
	protected SiebButtonTestObject Siguiente(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Siguiente"), anchor, flags);
	}
	
	

	protected AdministrarFacilidadesCMHelper()
	{
		setScriptName("Scripts.Comun.AdministrarFacilidadesCM");
	}
	
}

