// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>AgregarRepLegal</b><br>
 * Generated     : <b>2017/07/13 12:20:14 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  julio 13, 2017
 * @author rft
 */
public abstract class AgregarRepLegalHelper extends libreria.Accion
{
	/**
	 * HIQuery: with default state.
	 *		ClassName : SiebToolbar
	 * 		.class : SiebToolbar
	 * 		RepositoryName : HIQuery
	 */
	protected SiebToolbarTestObject HIQuery() 
	{
		return new SiebToolbarTestObject(
                        getMappedTestObject("HIQuery"));
	}
	/**
	 * HIQuery: with specific test context and state.
	 *		ClassName : SiebToolbar
	 * 		.class : SiebToolbar
	 * 		RepositoryName : HIQuery
	 */
	protected SiebToolbarTestObject HIQuery(TestObject anchor, long flags) 
	{
		return new SiebToolbarTestObject(
                        getMappedTestObject("HIQuery"), anchor, flags);
	}
	
	/**
	 * Identificacion: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Social Security Number
	 */
	protected SiebTextTestObject Identificacion() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Identificacion"));
	}
	/**
	 * Identificacion: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Social Security Number
	 */
	protected SiebTextTestObject Identificacion(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Identificacion"), anchor, flags);
	}
	
	/**
	 * NewQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NewQuery() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NewQuery"));
	}
	/**
	 * NewQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NewQuery(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NewQuery"), anchor, flags);
	}
	
	/**
	 * PickRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : PickRecord
	 */
	protected SiebButtonTestObject PickRecord() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("PickRecord"));
	}
	/**
	 * PickRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : PickRecord
	 */
	protected SiebButtonTestObject PickRecord(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("PickRecord"), anchor, flags);
	}
	
	/**
	 * RepLegal: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : MVG Last Name
	 */
	protected SiebTextTestObject RepLegal() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("RepLegal"));
	}
	/**
	 * RepLegal: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : MVG Last Name
	 */
	protected SiebTextTestObject RepLegal(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("RepLegal"), anchor, flags);
	}
	
	/**
	 * 3.- SiebelApp -- SS Ult Modif ss 16 Junio 2017                                            : with default state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel() 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"));
	}
	/**
	 * 3.- SiebelApp -- SS Ult Modif ss 16 Junio 2017                                            : with specific test context and state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel(TestObject anchor, long flags) 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"), anchor, flags);
	}
	
	

	protected AgregarRepLegalHelper()
	{
		setScriptName("Scripts.Comun.AgregarRepLegal");
	}
	
}

