// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BorrarIMEI</b><br>
 * Generated     : <b>2016/12/16 3:24:51 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 16, 2016
 * @author rft
 */
public abstract class BorrarIMEIHelper extends libreria.Accion
{
	/**
	 * Description: with default state.
	 *		ClassName : SiebTextArea
	 * 		.class : SiebTextArea
	 * 		RepositoryName : Description
	 */
	protected SiebTextAreaTestObject Descripcion() 
	{
		return new SiebTextAreaTestObject(
                        getMappedTestObject("Descripcion"));
	}
	/**
	 * Description: with specific test context and state.
	 *		ClassName : SiebTextArea
	 * 		.class : SiebTextArea
	 * 		RepositoryName : Description
	 */
	protected SiebTextAreaTestObject Descripcion(TestObject anchor, long flags) 
	{
		return new SiebTextAreaTestObject(
                        getMappedTestObject("Descripcion"), anchor, flags);
	}
	
	/**
	 * IMEI: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMEI
	 */
	protected SiebTextTestObject IMEI() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMEI"));
	}
	/**
	 * IMEI: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMEI
	 */
	protected SiebTextTestObject IMEI(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMEI"), anchor, flags);
	}
	
	/**
	 * IMEI_PI: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMEI
	 */
	protected SiebTextTestObject IMEI_PI() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMEI_PI"));
	}
	/**
	 * IMEI_PI: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMEI
	 */
	protected SiebTextTestObject IMEI_PI(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMEI_PI"), anchor, flags);
	}
	
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * LineasPedidoPI: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedidoPI() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedidoPI"));
	}
	/**
	 * LineasPedidoPI: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedidoPI(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedidoPI"), anchor, flags);
	}
	
	/**
	 * SiebelPowerCommunications: with default state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel() 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"));
	}
	/**
	 * SiebelPowerCommunications: with specific test context and state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel(TestObject anchor, long flags) 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"), anchor, flags);
	}
	
	

	protected BorrarIMEIHelper()
	{
		setScriptName("Scripts.Comun.BorrarIMEI");
	}
	
}

