// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BuscaryValidarProductoREDCM</b><br>
 * Generated     : <b>2017/02/13 2:09:58 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  febrero 13, 2017
 * @author rft
 */
public abstract class BuscaryValidarProductoREDCMHelper extends libreria.Accion
{
	/**
	 * AppletRED: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE RED Configure List Applet
	 */
	protected SiebAppletTestObject AppletRED() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletRED"));
	}
	/**
	 * AppletRED: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE RED Configure List Applet
	 */
	protected SiebAppletTestObject AppletRED(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletRED"), anchor, flags);
	}
	
	/**
	 * ListaRED: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaRED() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaRED"));
	}
	/**
	 * ListaRED: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaRED(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaRED"), anchor, flags);
	}
	
	/**
	 * PriceValueCalc: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Price Value Calc
	 */
	protected SiebTextTestObject Precio() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Precio"));
	}
	/**
	 * PriceValueCalc: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Price Value Calc
	 */
	protected SiebTextTestObject Precio(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Precio"), anchor, flags);
	}
	
	/**
	 * ProdName: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Prod Name
	 */
	protected SiebTextTestObject Producto() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Producto"));
	}
	/**
	 * ProdName: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Prod Name
	 */
	protected SiebTextTestObject Producto(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Producto"), anchor, flags);
	}
	
	/**
	 * RedFlg: with default state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : Red Flg
	 */
	protected SiebCheckboxTestObject aRED() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("aRED"));
	}
	/**
	 * RedFlg: with specific test context and state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : Red Flg
	 */
	protected SiebCheckboxTestObject aRED(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("aRED"), anchor, flags);
	}
	
	

	protected BuscaryValidarProductoREDCMHelper()
	{
		setScriptName("Scripts.Comun.BuscaryValidarProductoREDCM");
	}
	
}

