// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BuscarProducto</b><br>
 * Generated     : <b>2017/07/03 15:55:30</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  julio 03, 2017
 * @author Sandra
 */
public abstract class BuscarProductoHelper extends libreria.Accion
{
	/**
	 * AppletLineasPedido: with default state.
	 *		RecordCounter : 1 - 10 of 21
	 * 		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : Order Entry - Line Item List Applet (Sales)
	 */
	protected SiebAppletTestObject AppletLineasPedido() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletLineasPedido"));
	}
	/**
	 * AppletLineasPedido: with specific test context and state.
	 *		RecordCounter : 1 - 10 of 21
	 * 		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : Order Entry - Line Item List Applet (Sales)
	 */
	protected SiebAppletTestObject AppletLineasPedido(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletLineasPedido"), anchor, flags);
	}
	
	/**
	 * AppletLineasPedidoPI: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE Port Entry - Line Item List Applet (Sales)
	 */
	protected SiebAppletTestObject AppletLineasPedidoPI() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletLineasPedidoPI"));
	}
	/**
	 * AppletLineasPedidoPI: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE Port Entry - Line Item List Applet (Sales)
	 */
	protected SiebAppletTestObject AppletLineasPedidoPI(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletLineasPedidoPI"), anchor, flags);
	}
	
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * LineasPedidoPI: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedidoPI() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedidoPI"));
	}
	/**
	 * LineasPedidoPI: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedidoPI(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedidoPI"), anchor, flags);
	}
	
	/**
	 * Menu: with default state.
	 *		.text : Menú
	 * 		.id : s_at_m_3
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Menu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Menu"));
	}
	/**
	 * Menu: with specific test context and state.
	 *		.text : Menú
	 * 		.id : s_at_m_3
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Menu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Menu"), anchor, flags);
	}
	
	/**
	 * MenuOLD: with default state.
	 *		.text : Menú
	 * 		.id : s_at_m_3
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject MenuOld() 
	{
		return new GuiTestObject(
                        getMappedTestObject("MenuOld"));
	}
	/**
	 * MenuOLD: with specific test context and state.
	 *		.text : Menú
	 * 		.id : s_at_m_3
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject MenuOld(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("MenuOld"), anchor, flags);
	}
	
	/**
	 * MenuPI: with default state.
	 *		.text : Menú
	 * 		.href : javascript:void(0)
	 * 		.id : s_at_m_5
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject MenuPI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("MenuPI"));
	}
	/**
	 * MenuPI: with specific test context and state.
	 *		.text : Menú
	 * 		.href : javascript:void(0)
	 * 		.id : s_at_m_5
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject MenuPI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("MenuPI"), anchor, flags);
	}
	
	/**
	 * NroLinea: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Outline Number
	 */
	protected SiebTextTestObject NroLinea() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroLinea"));
	}
	/**
	 * NroLinea: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Outline Number
	 */
	protected SiebTextTestObject NroLinea(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroLinea"), anchor, flags);
	}
	
	/**
	 * TabsPedidoPortabilidad: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject TabsPedidoPortabilidad() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("TabsPedidoPortabilidad"));
	}
	/**
	 * TabsPedidoPortabilidad: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject TabsPedidoPortabilidad(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("TabsPedidoPortabilidad"), anchor, flags);
	}
	
	/**
	 * TabsPedidoVta: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject TabsPedidoVta() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("TabsPedidoVta"));
	}
	/**
	 * TabsPedidoVta: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject TabsPedidoVta(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("TabsPedidoVta"), anchor, flags);
	}
	
	

	protected BuscarProductoHelper()
	{
		setScriptName("Scripts.Comun.BuscarProducto");
	}
	
}

