// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BuscarProductoActivoParc</b><br>
 * Generated     : <b>2017/05/03 1:54:02 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  mayo 03, 2017
 * @author rft
 */
public abstract class BuscarProductoActivoParcHelper extends libreria.Accion
{
	/**
	 * AppletLineasActivo: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : SIS OM Products & Services Root List Applet (Service) - Tiny
	 */
	protected SiebAppletTestObject AppletLineasActivo() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletLineasActivo"));
	}
	/**
	 * AppletLineasActivo: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : SIS OM Products & Services Root List Applet (Service) - Tiny
	 */
	protected SiebAppletTestObject AppletLineasActivo(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("AppletLineasActivo"), anchor, flags);
	}
	
	/**
	 * LineasActivoCtaFact: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasActivoCtaFact() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasActivoCtaFact"));
	}
	/**
	 * LineasActivoCtaFact: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasActivoCtaFact(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasActivoCtaFact"), anchor, flags);
	}
	
	/**
	 * ProductName: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Product Name
	 */
	protected SiebTextTestObject NombreProductoActivo() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreProductoActivo"));
	}
	/**
	 * ProductName: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Product Name
	 */
	protected SiebTextTestObject NombreProductoActivo(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreProductoActivo"), anchor, flags);
	}
	
	

	protected BuscarProductoActivoParcHelper()
	{
		setScriptName("Scripts.Comun.BuscarProductoActivoParc");
	}
	
}

