// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CambiarPerfil</b><br>
 * Generated     : <b>2016/04/04 11:36:26</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 04, 2016
 * @author Sandra
 */
public abstract class CambiarPerfilHelper extends libreria.Accion
{
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * LineasPedidoPI: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedidoPI() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedidoPI"));
	}
	/**
	 * LineasPedidoPI: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedidoPI(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedidoPI"), anchor, flags);
	}
	
	/**
	 * TipoPago: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Payment Type
	 */
	protected SiebPicklistTestObject TipoPago() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoPago"));
	}
	/**
	 * TipoPago: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Payment Type
	 */
	protected SiebPicklistTestObject TipoPago(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoPago"), anchor, flags);
	}
	
	/**
	 * TIpoPagoCtaCte: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Payment Type
	 */
	protected SiebPicklistTestObject TipoPagoCtaCte() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoPagoCtaCte"));
	}
	/**
	 * TIpoPagoCtaCte: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Payment Type
	 */
	protected SiebPicklistTestObject TipoPagoCtaCte(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoPagoCtaCte"), anchor, flags);
	}
	
	/**
	 * TipoPagoHibrido: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Payment Type
	 */
	protected SiebPicklistTestObject TipoPagoHibrido() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoPagoHibrido"));
	}
	/**
	 * TipoPagoHibrido: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Payment Type
	 */
	protected SiebPicklistTestObject TipoPagoHibrido(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoPagoHibrido"), anchor, flags);
	}
	
	

	protected CambiarPerfilHelper()
	{
		setScriptName("Scripts.Comun.CambiarPerfil");
	}
	
}

