// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CapturarHistoricoCambioPlan</b><br>
 * Generated     : <b>2017/07/12 11:39:30 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  julio 12, 2017
 * @author rft
 */
public abstract class CapturarHistoricoCambioPlanHelper extends libreria.Accion
{
	/**
	 * Pestañas: with default state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject Pestañas() 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * Pestañas: with specific test context and state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * SerialNum: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : SerialNum
	 */
	protected SiebTextTestObject Servicio() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Servicio"));
	}
	/**
	 * SerialNum: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : SerialNum
	 */
	protected SiebTextTestObject Servicio(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Servicio"), anchor, flags);
	}
	
	/**
	 * TabsCliente: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject SiebScreenViews() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("SiebScreenViews"));
	}
	/**
	 * TabsCliente: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject SiebScreenViews(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("SiebScreenViews"), anchor, flags);
	}
	
	/**
	 * ICEDetalleCPApplet: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE Detalle CP Applet
	 */
	protected SiebAppletTestObject applet_iceDetalleCPApplet() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("applet_iceDetalleCPApplet"));
	}
	/**
	 * ICEDetalleCPApplet: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ICE Detalle CP Applet
	 */
	protected SiebAppletTestObject applet_iceDetalleCPApplet(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("applet_iceDetalleCPApplet"), anchor, flags);
	}
	
	/**
	 * Consulta: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Consulta
	 */
	protected SiebButtonTestObject button_consulta() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_consulta"));
	}
	/**
	 * Consulta: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Consulta
	 */
	protected SiebButtonTestObject button_consulta(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_consulta"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject list_siebList() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("list_siebList"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject list_siebList(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("list_siebList"), anchor, flags);
	}
	
	

	protected CapturarHistoricoCambioPlanHelper()
	{
		setScriptName("Scripts.Comun.CapturarHistoricoCambioPlan");
	}
	
}

