// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CrearListaEspecial1</b><br>
 * Generated     : <b>2016/10/20 16:50:33</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  octubre 20, 2016
 * @author Sandra
 */
public abstract class CrearListaEspecial1Helper extends libreria.Accion
{
	/**
	 * HtmlTable: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject AppletSuperior() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("AppletSuperior"));
	}
	/**
	 * HtmlTable: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject AppletSuperior(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("AppletSuperior"), anchor, flags);
	}
	
	/**
	 * IESiebel: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.documentName : RegularExpression(http.*\/ecommunications_esn/star.*)
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject BrowserIE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("BrowserIE"));
	}
	/**
	 * IESiebel: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.documentName : RegularExpression(http.*\/ecommunications_esn/star.*)
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject BrowserIE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("BrowserIE"), anchor, flags);
	}
	
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListType: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"));
	}
	/**
	 * SpecialRatingListType: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListName: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"));
	}
	/**
	 * SpecialRatingListName: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"), anchor, flags);
	}
	
	/**
	 * NewRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLista() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLista"));
	}
	/**
	 * NewRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLista(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLista"), anchor, flags);
	}
	
	/**
	 * NewRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevoNumero() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevoNumero"));
	}
	/**
	 * NewRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevoNumero(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevoNumero"), anchor, flags);
	}
	
	/**
	 * PhoneNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Phone Number
	 */
	protected SiebTextTestObject NumTel() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NumTel"));
	}
	/**
	 * PhoneNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Phone Number
	 */
	protected SiebTextTestObject NumTel(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NumTel"), anchor, flags);
	}
	
	/**
	 * TabsCliente: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject Pestañas() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * TabsCliente: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * SSAPrimaryField: with default state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : SSA Primary Field
	 */
	protected SiebCheckboxTestObject Primaria() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Primaria"));
	}
	/**
	 * SSAPrimaryField: with specific test context and state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : SSA Primary Field
	 */
	protected SiebCheckboxTestObject Primaria(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Primaria"), anchor, flags);
	}
	
	/**
	 * SiebelPowerCommunications: with default state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel() 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"));
	}
	/**
	 * SiebelPowerCommunications: with specific test context and state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel(TestObject anchor, long flags) 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"), anchor, flags);
	}
	
	/**
	 * SiebelCommunications_Login: with default state.
	 *		.title : Siebel Communications
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*ecommunications_esn/start.*)
	 */
	protected DocumentTestObject SiebelDoc() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("SiebelDoc"));
	}
	/**
	 * SiebelCommunications_Login: with specific test context and state.
	 *		.title : Siebel Communications
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*ecommunications_esn/start.*)
	 */
	protected DocumentTestObject SiebelDoc(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("SiebelDoc"), anchor, flags);
	}
	
	/**
	 * SWISpecialRatingItemsListApplet: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : SWI Special Rating Items List Applet
	 */
	protected SiebAppletTestObject SpecialRatingItemsApplet() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("SpecialRatingItemsApplet"));
	}
	/**
	 * SWISpecialRatingItemsListApplet: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : SWI Special Rating Items List Applet
	 */
	protected SiebAppletTestObject SpecialRatingItemsApplet(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("SpecialRatingItemsApplet"), anchor, flags);
	}
	
	/**
	 * Tabla HTML DIV de Numeros de Lista Especial: with default state.
	 *		.id : s_S_A3_div
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject TablaHTMLDIVdeNumListaEsp() 
	{
		return new GuiTestObject(
                        getMappedTestObject("TablaHTMLDIVdeNumListaEsp"));
	}
	/**
	 * Tabla HTML DIV de Numeros de Lista Especial: with specific test context and state.
	 *		.id : s_S_A3_div
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject TablaHTMLDIVdeNumListaEsp(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("TablaHTMLDIVdeNumListaEsp"), anchor, flags);
	}
	
	/**
	 * SiebThreadbar: with default state.
	 *		ClassName : SiebThreadbar
	 * 		.class : SiebThreadbar
	 * 		RepositoryName : SiebThreadbar
	 */
	protected SiebThreadbarTestObject Threadbar() 
	{
		return new SiebThreadbarTestObject(
                        getMappedTestObject("Threadbar"));
	}
	/**
	 * SiebThreadbar: with specific test context and state.
	 *		ClassName : SiebThreadbar
	 * 		.class : SiebThreadbar
	 * 		RepositoryName : SiebThreadbar
	 */
	protected SiebThreadbarTestObject Threadbar(TestObject anchor, long flags) 
	{
		return new SiebThreadbarTestObject(
                        getMappedTestObject("Threadbar"), anchor, flags);
	}
	
	/**
	 * SWISpecialRatingProfileView: with default state.
	 *		ClassName : SiebView
	 * 		.class : SiebView
	 * 		RepositoryName : SWI Special Rating Profile View
	 */
	protected SiebViewTestObject VistaListaEspecial() 
	{
		return new SiebViewTestObject(
                        getMappedTestObject("VistaListaEspecial"));
	}
	/**
	 * SWISpecialRatingProfileView: with specific test context and state.
	 *		ClassName : SiebView
	 * 		.class : SiebView
	 * 		RepositoryName : SWI Special Rating Profile View
	 */
	protected SiebViewTestObject VistaListaEspecial(TestObject anchor, long flags) 
	{
		return new SiebViewTestObject(
                        getMappedTestObject("VistaListaEspecial"), anchor, flags);
	}
	
	/**
	 * ExecuteQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject button_executeQuery() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_executeQuery"));
	}
	/**
	 * ExecuteQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject button_executeQuery(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_executeQuery"), anchor, flags);
	}
	
	/**
	 * NewQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject button_newQuery() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_newQuery"));
	}
	/**
	 * NewQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject button_newQuery(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_newQuery"), anchor, flags);
	}
	
	/**
	 * s_4_1_87_0: with default state.
	 *		.id : s_4_1_87_0
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_s_4_1_87_0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_s_4_1_87_0"));
	}
	/**
	 * s_4_1_87_0: with specific test context and state.
	 *		.id : s_4_1_87_0
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_s_4_1_87_0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_s_4_1_87_0"), anchor, flags);
	}
	
	/**
	 * s_2_1_2_0_mb: with default state.
	 *		.text : Eliminar
	 * 		.id : s_2_1_2_0_mb
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_s_2_1_2_0_mb() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_2_1_2_0_mb"));
	}
	/**
	 * s_2_1_2_0_mb: with specific test context and state.
	 *		.text : Eliminar
	 * 		.id : s_2_1_2_0_mb
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_s_2_1_2_0_mb(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_2_1_2_0_mb"), anchor, flags);
	}
	
	/**
	 * BtonNuevo: with default state.
	 *		.text : Nuevo
	 * 		.id : s_2_1_8_0_mb
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_s_2_1_8_0_mb() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_2_1_8_0_mb"));
	}
	/**
	 * BtonNuevo: with specific test context and state.
	 *		.text : Nuevo
	 * 		.id : s_2_1_8_0_mb
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_s_2_1_8_0_mb(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_s_2_1_8_0_mb"), anchor, flags);
	}
	
	/**
	 * HtmlTable_2: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 2
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_2"));
	}
	/**
	 * HtmlTable_2: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 2
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_2"), anchor, flags);
	}
	
	/**
	 * AccountNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Account Number
	 */
	protected SiebTextTestObject text_accountNumber() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("text_accountNumber"));
	}
	/**
	 * AccountNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Account Number
	 */
	protected SiebTextTestObject text_accountNumber(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("text_accountNumber"), anchor, flags);
	}
	
	

	protected CrearListaEspecial1Helper()
	{
		setScriptName("Scripts.Comun.CrearListaEspecial1");
	}
	
}

