// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CrearLE</b><br>
 * Generated     : <b>2017/04/11 10:40:44 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 11, 2017
 * @author rft
 */
public abstract class CrearLEHelper extends libreria.Accion
{
	/**
	 * BtonNuevo: with default state.
	 *		.text : Nuevo
	 * 		.id : s_2_1_8_0_mb
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonNuevo() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonNuevo"));
	}
	/**
	 * BtonNuevo: with specific test context and state.
	 *		.text : Nuevo
	 * 		.id : s_2_1_8_0_mb
	 * 		.href : javascript:void(0)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonNuevo(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonNuevo"), anchor, flags);
	}
	
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * LineasPedidoPI: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedido_PI() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido_PI"));
	}
	/**
	 * LineasPedidoPI: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject LineasPedido_PI(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido_PI"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListType: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"));
	}
	/**
	 * SpecialRatingListType: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"), anchor, flags);
	}
	
	/**
	 * LE: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Listas() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Listas"));
	}
	/**
	 * LE: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Listas(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Listas"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListName: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"));
	}
	/**
	 * SpecialRatingListName: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"), anchor, flags);
	}
	
	/**
	 * NewRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLista() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLista"));
	}
	/**
	 * NewRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLista(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLista"), anchor, flags);
	}
	
	/**
	 * NumerosMenu: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject NumerosMenu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("NumerosMenu"));
	}
	/**
	 * NumerosMenu: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject NumerosMenu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("NumerosMenu"), anchor, flags);
	}
	
	/**
	 * TabsCliente: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject Pestañas() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * TabsCliente: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * SSAPrimaryField: with default state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : SSA Primary Field
	 */
	protected SiebCheckboxTestObject Primaria() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Primaria"));
	}
	/**
	 * SSAPrimaryField: with specific test context and state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : SSA Primary Field
	 */
	protected SiebCheckboxTestObject Primaria(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Primaria"), anchor, flags);
	}
	
	

	protected CrearLEHelper()
	{
		setScriptName("Scripts.Comun.CrearLE");
	}
	
}

