// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CrearListaEspecial</b><br>
 * Generated     : <b>2016/01/15 11:51:52</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 15, 2016
 * @author Sandra
 */
public abstract class CrearListaEspecialHelper extends libreria.Accion
{
	/**
	 * Arbol_lista: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * Arbol_lista: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListType: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"));
	}
	/**
	 * SpecialRatingListType: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListName: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"));
	}
	/**
	 * SpecialRatingListName: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"), anchor, flags);
	}
	
	/**
	 * NewRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLista() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLista"));
	}
	/**
	 * NewRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLista(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLista"), anchor, flags);
	}
	
	/**
	 * NewRecord: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevoNumero() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevoNumero"));
	}
	/**
	 * NewRecord: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevoNumero(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevoNumero"), anchor, flags);
	}
	
	/**
	 * PhoneNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Phone Number
	 */
	protected SiebTextTestObject NumTel() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NumTel"));
	}
	/**
	 * PhoneNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Phone Number
	 */
	protected SiebTextTestObject NumTel(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NumTel"), anchor, flags);
	}
	
	/**
	 * SiebScreenViews: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject Pestañas() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * SiebScreenViews: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * SSAPrimaryField: with default state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : SSA Primary Field
	 */
	protected SiebCheckboxTestObject Primaria() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Primaria"));
	}
	/**
	 * SSAPrimaryField: with specific test context and state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : SSA Primary Field
	 */
	protected SiebCheckboxTestObject Primaria(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("Primaria"), anchor, flags);
	}
	
	/**
	 * SiebelPowerCommunications: with default state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel() 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"));
	}
	/**
	 * SiebelPowerCommunications: with specific test context and state.
	 *		ClassName : SiebApplication
	 * 		.class : SiebApplication
	 * 		RepositoryName : Siebel Power Communications
	 */
	protected SiebApplicationTestObject Siebel(TestObject anchor, long flags) 
	{
		return new SiebApplicationTestObject(
                        getMappedTestObject("Siebel"), anchor, flags);
	}
	
	/**
	 * Tabla HTML DIV de Numeros de Lista Especial: with default state.
	 *		.id : s_S_A3_div
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject TablaHTMLDIVdeNumListaEsp() 
	{
		return new GuiTestObject(
                        getMappedTestObject("TablaHTMLDIVdeNumListaEsp"));
	}
	/**
	 * Tabla HTML DIV de Numeros de Lista Especial: with specific test context and state.
	 *		.id : s_S_A3_div
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject TablaHTMLDIVdeNumListaEsp(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("TablaHTMLDIVdeNumListaEsp"), anchor, flags);
	}
	
	/**
	 * SiebThreadbar: with default state.
	 *		ClassName : SiebThreadbar
	 * 		.class : SiebThreadbar
	 * 		RepositoryName : SiebThreadbar
	 */
	protected SiebThreadbarTestObject Threadbar() 
	{
		return new SiebThreadbarTestObject(
                        getMappedTestObject("Threadbar"));
	}
	/**
	 * SiebThreadbar: with specific test context and state.
	 *		ClassName : SiebThreadbar
	 * 		.class : SiebThreadbar
	 * 		RepositoryName : SiebThreadbar
	 */
	protected SiebThreadbarTestObject Threadbar(TestObject anchor, long flags) 
	{
		return new SiebThreadbarTestObject(
                        getMappedTestObject("Threadbar"), anchor, flags);
	}
	
	

	protected CrearListaEspecialHelper()
	{
		setScriptName("Scripts.Comun.CrearListaEspecial");
	}
	
}

