// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CrearLENew</b><br>
 * Generated     : <b>2016/12/21 12:30:08</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 21, 2016
 * @author Sandra
 */
public abstract class CrearLENewHelper extends libreria.Accion
{
	/**
	 * BtonConsultaPedido: with default state.
	 *		.text : Consulta
	 * 		.href : javascript:void(0)
	 * 		.id : s_1_1_151_0_mb
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultaPedido() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultaPedido"));
	}
	/**
	 * BtonConsultaPedido: with specific test context and state.
	 *		.text : Consulta
	 * 		.href : javascript:void(0)
	 * 		.id : s_1_1_151_0_mb
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultaPedido(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultaPedido"), anchor, flags);
	}
	
	/**
	 * BtonConsultaPedidoPI: with default state.
	 *		.text : Consulta
	 * 		.href : javascript:void(0)
	 * 		.id : s_4_1_152_0_mb
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultaPedidoPI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultaPedidoPI"));
	}
	/**
	 * BtonConsultaPedidoPI: with specific test context and state.
	 *		.text : Consulta
	 * 		.href : javascript:void(0)
	 * 		.id : s_4_1_152_0_mb
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultaPedidoPI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultaPedidoPI"), anchor, flags);
	}
	
	/**
	 * LE: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject EncabezadoLE() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("EncabezadoLE"));
	}
	/**
	 * LE: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject EncabezadoLE(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("EncabezadoLE"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListType: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"));
	}
	/**
	 * SpecialRatingListType: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Special Rating List Type
	 */
	protected SiebPicklistTestObject ListaEsp(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("ListaEsp"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaEspecial(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaEspecial"), anchor, flags);
	}
	
	/**
	 * SpecialRatingListName: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"));
	}
	/**
	 * SpecialRatingListName: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Special Rating List Name
	 */
	protected SiebTextTestObject NombreLE(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NombreLE"), anchor, flags);
	}
	
	/**
	 * NuevaLE: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLE() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLE"));
	}
	/**
	 * NuevaLE: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewRecord
	 */
	protected SiebButtonTestObject NuevaLE(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaLE"), anchor, flags);
	}
	
	/**
	 * NumerosLE: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : SWEForm3_0
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NumerosLE() 
	{
		return new GuiTestObject(
                        getMappedTestObject("NumerosLE"));
	}
	/**
	 * NumerosLE: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : SWEForm3_0
	 * 		.classIndex : 0
	 */
	protected GuiTestObject NumerosLE(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("NumerosLE"), anchor, flags);
	}
	
	/**
	 * TabsPedidoVta: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject SubPestañas() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("SubPestañas"));
	}
	/**
	 * TabsPedidoVta: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject SubPestañas(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("SubPestañas"), anchor, flags);
	}
	
	

	protected CrearLENewHelper()
	{
		setScriptName("Scripts.Comun.CrearLENew");
	}
	
}

