// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>EsperaEventoCM</b><br>
 * Generated     : <b>2016/04/28 10:04:46</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 28, 2016
 * @author Sandra
 */
public abstract class EsperaEventoCMHelper extends libreria.Accion
{
	/**
	 * EstadoRED: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : EstadoRED
	 */
	protected SiebTextTestObject EstadoRED() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("EstadoRED"));
	}
	/**
	 * EstadoRED: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : EstadoRED
	 */
	protected SiebTextTestObject EstadoRED(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("EstadoRED"), anchor, flags);
	}
	
	/**
	 * TaskStep: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Task Step
	 */
	protected SiebTextTestObject EstadoTarea() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("EstadoTarea"));
	}
	/**
	 * TaskStep: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Task Step
	 */
	protected SiebTextTestObject EstadoTarea(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("EstadoTarea"), anchor, flags);
	}
	
	/**
	 * Estado_Tramite: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Estado_Tramite
	 */
	protected SiebTextTestObject EstadoTramite() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("EstadoTramite"));
	}
	/**
	 * Estado_Tramite: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Estado_Tramite
	 */
	protected SiebTextTestObject EstadoTramite(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("EstadoTramite"), anchor, flags);
	}
	
	/**
	 * HIQuery: with default state.
	 *		ClassName : SiebToolbar
	 * 		.class : SiebToolbar
	 * 		RepositoryName : HIQuery
	 */
	protected SiebToolbarTestObject HiQuery() 
	{
		return new SiebToolbarTestObject(
                        getMappedTestObject("HiQuery"));
	}
	/**
	 * HIQuery: with specific test context and state.
	 *		ClassName : SiebToolbar
	 * 		.class : SiebToolbar
	 * 		RepositoryName : HIQuery
	 */
	protected SiebToolbarTestObject HiQuery(TestObject anchor, long flags) 
	{
		return new SiebToolbarTestObject(
                        getMappedTestObject("HiQuery"), anchor, flags);
	}
	
	/**
	 * PedidosCM: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject PedidosCM() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("PedidosCM"));
	}
	/**
	 * PedidosCM: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject PedidosCM(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("PedidosCM"), anchor, flags);
	}
	
	/**
	 * Tipo_Tramite: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Tipo_Tramite
	 */
	protected SiebTextTestObject Tipo_Tramite() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Tipo_Tramite"));
	}
	/**
	 * Tipo_Tramite: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Tipo_Tramite
	 */
	protected SiebTextTestObject Tipo_Tramite(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Tipo_Tramite"), anchor, flags);
	}
	
	

	protected EsperaEventoCMHelper()
	{
		setScriptName("Scripts.Comun.EsperaEventoCM");
	}
	
}

