// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>IngresarAutenticacion</b><br>
 * Generated     : <b>2016/01/27 11:30:02</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 27, 2016
 * @author Sandra
 */
public abstract class IngresarAutenticacionHelper extends libreria.Accion
{
	/**
	 * Linea_del_menu Encabezado Pedido: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject BotonesPedidoEncabezado() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("BotonesPedidoEncabezado"));
	}
	/**
	 * Linea_del_menu Encabezado Pedido: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject BotonesPedidoEncabezado(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("BotonesPedidoEncabezado"), anchor, flags);
	}
	
	/**
	 * ICEChannelId: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : ICE Channel Id
	 */
	protected SiebPicklistTestObject Canal() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("Canal"));
	}
	/**
	 * ICEChannelId: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : ICE Channel Id
	 */
	protected SiebPicklistTestObject Canal(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("Canal"), anchor, flags);
	}
	
	/**
	 * ICEAuthenticationType: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : ICE Authentication Type
	 */
	protected SiebPicklistTestObject TipoAutenticacion() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoAutenticacion"));
	}
	/**
	 * ICEAuthenticationType: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : ICE Authentication Type
	 */
	protected SiebPicklistTestObject TipoAutenticacion(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("TipoAutenticacion"), anchor, flags);
	}
	
	/**
	 * Detalles: with default state.
	 *		.title : Detalles
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*\/ecommunications_esn/start\.swe\?SWECmd=GetViewLayout ...
	 */
	protected DocumentTestObject document_detalles() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_detalles"));
	}
	/**
	 * Detalles: with specific test context and state.
	 *		.title : Detalles
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*\/ecommunications_esn/start\.swe\?SWECmd=GetViewLayout ...
	 */
	protected DocumentTestObject document_detalles(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_detalles"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point ICEAuthenticationType_list object in the SUT.
	 */
	protected IFtVerificationPoint ICEAuthenticationType_listVP() 
	{
		return vp("ICEAuthenticationType_list");
	}
	protected IFtVerificationPoint ICEAuthenticationType_listVP(TestObject anchor)
	{
		return vp("ICEAuthenticationType_list", anchor);
	}
	
	

	protected IngresarAutenticacionHelper()
	{
		setScriptName("Scripts.Comun.IngresarAutenticacion");
	}
	
}

