// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>LiberarNumero</b><br>
 * Generated     : <b>2016/01/07 22:01:31</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 07, 2016
 * @author Sandra
 */
public abstract class LiberarNumeroHelper extends libreria.Accion
{
	/**
	 * AceptarMensajeHTMLSiebel: with default state.
	 *		.text : RegularExpression((Aceptar|OK))
	 * 		.class : Html.DialogButton
	 * 		.disabled : false
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensaje() 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensaje"));
	}
	/**
	 * AceptarMensajeHTMLSiebel: with specific test context and state.
	 *		.text : RegularExpression((Aceptar|OK))
	 * 		.class : Html.DialogButton
	 * 		.disabled : false
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensaje(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensaje"), anchor, flags);
	}
	
	/**
	 * ICEReleaseNumber: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEReleaseNumber
	 */
	protected SiebButtonTestObject LiberarNum() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("LiberarNum"));
	}
	/**
	 * ICEReleaseNumber: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEReleaseNumber
	 */
	protected SiebButtonTestObject LiberarNum(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("LiberarNum"), anchor, flags);
	}
	
	

	protected LiberarNumeroHelper()
	{
		setScriptName("Scripts.Comun.LiberarNumero");
	}
	
}

