// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>NuevoCambioPlan</b><br>
 * Generated     : <b>2016/01/27 12:28:40</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 27, 2016
 * @author Sandra
 */
public abstract class NuevoCambioPlanHelper extends libreria.Accion
{
	/**
	 * Execute: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Execute
	 */
	protected SiebButtonTestObject Aceptar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Aceptar"));
	}
	/**
	 * Execute: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Execute
	 */
	protected SiebButtonTestObject Aceptar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Aceptar"), anchor, flags);
	}
	
	/**
	 * EncabezadoPedido: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 3
	 */
	protected StatelessGuiSubitemTestObject EncabezadoPedido() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("EncabezadoPedido"));
	}
	/**
	 * EncabezadoPedido: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 3
	 */
	protected StatelessGuiSubitemTestObject EncabezadoPedido(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("EncabezadoPedido"), anchor, flags);
	}
	
	/**
	 * Detalles: with default state.
	 *		.title : Detalles
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*\/ecommunications_esn/start\.swe\?SWECmd=GetViewLayout ...
	 */
	protected DocumentTestObject EncabezadoPedidoHTML() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("EncabezadoPedidoHTML"));
	}
	/**
	 * Detalles: with specific test context and state.
	 *		.title : Detalles
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*\/ecommunications_esn/start\.swe\?SWECmd=GetViewLayout ...
	 */
	protected DocumentTestObject EncabezadoPedidoHTML(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("EncabezadoPedidoHTML"), anchor, flags);
	}
	
	/**
	 * OrderNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"));
	}
	/**
	 * OrderNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject PlanesDestino() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("PlanesDestino"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject PlanesDestino(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("PlanesDestino"), anchor, flags);
	}
	
	/**
	 * ISSPromotionUpgradePopupApplet: with default state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ISS Promotion Upgrade Popup Applet
	 */
	protected SiebAppletTestObject PromotionUpgradePopupApplet() 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("PromotionUpgradePopupApplet"));
	}
	/**
	 * ISSPromotionUpgradePopupApplet: with specific test context and state.
	 *		ClassName : SiebApplet
	 * 		.class : SiebApplet
	 * 		RepositoryName : ISS Promotion Upgrade Popup Applet
	 */
	protected SiebAppletTestObject PromotionUpgradePopupApplet(TestObject anchor, long flags) 
	{
		return new SiebAppletTestObject(
                        getMappedTestObject("PromotionUpgradePopupApplet"), anchor, flags);
	}
	
	/**
	 * SiebMenu: with default state.
	 *		ClassName : SiebMenu
	 * 		.class : SiebMenu
	 * 		RepositoryName : SiebMenu
	 */
	protected SiebMenuTestObject SiebMenu() 
	{
		return new SiebMenuTestObject(
                        getMappedTestObject("SiebMenu"));
	}
	/**
	 * SiebMenu: with specific test context and state.
	 *		ClassName : SiebMenu
	 * 		.class : SiebMenu
	 * 		RepositoryName : SiebMenu
	 */
	protected SiebMenuTestObject SiebMenu(TestObject anchor, long flags) 
	{
		return new SiebMenuTestObject(
                        getMappedTestObject("SiebMenu"), anchor, flags);
	}
	
	/**
	 * OrderEntryLineItemsDetailViewSales: with default state.
	 *		ClassName : SiebView
	 * 		.class : SiebView
	 * 		RepositoryName : Order Entry - Line Items Detail View (Sales)
	 */
	protected SiebViewTestObject siebView_orderEntryLineItemsDe() 
	{
		return new SiebViewTestObject(
                        getMappedTestObject("siebView_orderEntryLineItemsDe"));
	}
	/**
	 * OrderEntryLineItemsDetailViewSales: with specific test context and state.
	 *		ClassName : SiebView
	 * 		.class : SiebView
	 * 		RepositoryName : Order Entry - Line Items Detail View (Sales)
	 */
	protected SiebViewTestObject siebView_orderEntryLineItemsDe(TestObject anchor, long flags) 
	{
		return new SiebViewTestObject(
                        getMappedTestObject("siebView_orderEntryLineItemsDe"), anchor, flags);
	}
	
	

	protected NuevoCambioPlanHelper()
	{
		setScriptName("Scripts.Comun.NuevoCambioPlan");
	}
	
}

