// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>NuevoCambioModalidad</b><br>
 * Generated     : <b>2016/01/19 11:58:23</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 19, 2016
 * @author Sandra
 */
public abstract class NuevoCambioModalidadHelper extends libreria.Accion
{
	/**
	 * ICEIndependenciaNumericaTaskUIICEIndependenciaNumericaTaskGroup: with default state.
	 *		ClassName : SiebTaskLink
	 * 		.class : SiebTaskLink
	 * 		RepositoryName : ICE Independencia Numerica Task UI|ICE Independencia Numerica Task Group
	 */
	protected SiebTaskLinkTestObject IndependenciaNumericaTaskUI() 
	{
		return new SiebTaskLinkTestObject(
                        getMappedTestObject("IndependenciaNumericaTaskUI"));
	}
	/**
	 * ICEIndependenciaNumericaTaskUIICEIndependenciaNumericaTaskGroup: with specific test context and state.
	 *		ClassName : SiebTaskLink
	 * 		.class : SiebTaskLink
	 * 		RepositoryName : ICE Independencia Numerica Task UI|ICE Independencia Numerica Task Group
	 */
	protected SiebTaskLinkTestObject IndependenciaNumericaTaskUI(TestObject anchor, long flags) 
	{
		return new SiebTaskLinkTestObject(
                        getMappedTestObject("IndependenciaNumericaTaskUI"), anchor, flags);
	}
	
	/**
	 * Pestañas: with default state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject Pestañas() 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * Pestañas: with specific test context and state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * Tareas: with default state.
	 *		.alt : Tareas
	 * 		.id : s_4_in0
	 * 		.src : RegularExpression(http://.*\/ecommunications_esn/images/icon_opentaskpane\.gif)
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Tareas() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Tareas"));
	}
	/**
	 * Tareas: with specific test context and state.
	 *		.alt : Tareas
	 * 		.id : s_4_in0
	 * 		.src : RegularExpression(http://.*\/ecommunications_esn/images/icon_opentaskpane\.gif)
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Tareas(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Tareas"), anchor, flags);
	}
	
	/**
	 * TaskUIPane: with default state.
	 *		ClassName : SiebTaskUIPane
	 * 		.class : SiebTaskUIPane
	 * 		RepositoryName : TaskUIPane
	 */
	protected SiebTaskUIPaneTestObject scrollPane_taskUIPane() 
	{
		return new SiebTaskUIPaneTestObject(
                        getMappedTestObject("scrollPane_taskUIPane"));
	}
	/**
	 * TaskUIPane: with specific test context and state.
	 *		ClassName : SiebTaskUIPane
	 * 		.class : SiebTaskUIPane
	 * 		RepositoryName : TaskUIPane
	 */
	protected SiebTaskUIPaneTestObject scrollPane_taskUIPane(TestObject anchor, long flags) 
	{
		return new SiebTaskUIPaneTestObject(
                        getMappedTestObject("scrollPane_taskUIPane"), anchor, flags);
	}
	
	

	protected NuevoCambioModalidadHelper()
	{
		setScriptName("Scripts.Comun.NuevoCambioModalidad");
	}
	
}

