// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PagarRED</b><br>
 * Generated     : <b>2016/02/16 08:29:45</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  febrero 16, 2016
 * @author Sandra
 */
public abstract class PagarREDHelper extends libreria.Accion
{
	/**
	 * EstadoPedido: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Status
	 */
	protected SiebPicklistTestObject EstadoPedido() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoPedido"));
	}
	/**
	 * EstadoPedido: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Status
	 */
	protected SiebPicklistTestObject EstadoPedido(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoPedido"), anchor, flags);
	}
	
	/**
	 * EstadoRED: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : ICEEstadoRED
	 */
	protected SiebPicklistTestObject EstadoRED() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoRED"));
	}
	/**
	 * EstadoRED: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : ICEEstadoRED
	 */
	protected SiebPicklistTestObject EstadoRED(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoRED"), anchor, flags);
	}
	
	/**
	 * ExecuteQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject ExecuteQuery() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("ExecuteQuery"));
	}
	/**
	 * ExecuteQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject ExecuteQuery(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("ExecuteQuery"), anchor, flags);
	}
	
	/**
	 * NewQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NewQuery() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NewQuery"));
	}
	/**
	 * NewQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NewQuery(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NewQuery"), anchor, flags);
	}
	
	/**
	 * NroPedido: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"));
	}
	/**
	 * NroPedido: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"), anchor, flags);
	}
	
	/**
	 * NroPedidoAdmin: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedidoAdmin() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedidoAdmin"));
	}
	/**
	 * NroPedidoAdmin: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedidoAdmin(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedidoAdmin"), anchor, flags);
	}
	
	/**
	 * NroRED: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Recipient Number
	 */
	protected SiebTextTestObject NroRED() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroRED"));
	}
	/**
	 * NroRED: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Recipient Number
	 */
	protected SiebTextTestObject NroRED(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroRED"), anchor, flags);
	}
	
	/**
	 * PestañasPedido: with default state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject PestañasPedido() 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("PestañasPedido"));
	}
	/**
	 * PestañasPedido: with specific test context and state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject PestañasPedido(TestObject anchor, long flags) 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("PestañasPedido"), anchor, flags);
	}
	
	/**
	 * Total: with default state.
	 *		ClassName : SiebCurrency
	 * 		.class : SiebCurrency
	 * 		RepositoryName : Total
	 */
	protected SiebCurrencyTestObject Total() 
	{
		return new SiebCurrencyTestObject(
                        getMappedTestObject("Total"));
	}
	/**
	 * Total: with specific test context and state.
	 *		ClassName : SiebCurrency
	 * 		.class : SiebCurrency
	 * 		RepositoryName : Total
	 */
	protected SiebCurrencyTestObject Total(TestObject anchor, long flags) 
	{
		return new SiebCurrencyTestObject(
                        getMappedTestObject("Total"), anchor, flags);
	}
	
	/**
	 * TotalAdmin: with default state.
	 *		ClassName : SiebCalculator
	 * 		.class : SiebCalculator
	 * 		RepositoryName : ICEMontoRED
	 */
	protected SiebCalculatorTestObject TotalAdmin() 
	{
		return new SiebCalculatorTestObject(
                        getMappedTestObject("TotalAdmin"));
	}
	/**
	 * TotalAdmin: with specific test context and state.
	 *		ClassName : SiebCalculator
	 * 		.class : SiebCalculator
	 * 		RepositoryName : ICEMontoRED
	 */
	protected SiebCalculatorTestObject TotalAdmin(TestObject anchor, long flags) 
	{
		return new SiebCalculatorTestObject(
                        getMappedTestObject("TotalAdmin"), anchor, flags);
	}
	
	

	protected PagarREDHelper()
	{
		setScriptName("Scripts.Comun.PagarRED");
	}
	
}

