// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PersonalizarPromOpc</b><br>
 * Generated     : <b>2016/12/21 12:35:21</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 21, 2016
 * @author Sandra
 */
public abstract class PersonalizarPromOpcHelper extends libreria.Accion
{
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * NoPaquetesMin: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject NoPaquetesMin() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("NoPaquetesMin"));
	}
	/**
	 * NoPaquetesMin: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject NoPaquetesMin(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("NoPaquetesMin"), anchor, flags);
	}
	
	/**
	 * NoPaquetesSMS: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject NoPaquetesSMS() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("NoPaquetesSMS"));
	}
	/**
	 * NoPaquetesSMS: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject NoPaquetesSMS(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("NoPaquetesSMS"), anchor, flags);
	}
	
	/**
	 * Paquetes: with default state.
	 *		.text : Paquetes
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId14", "ChangeCurrentObj","linkMethod ...
	 * 		.id : GRPITEM[~^`grpItemId14`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Paquetes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Paquetes"));
	}
	/**
	 * Paquetes: with specific test context and state.
	 *		.text : Paquetes
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId14", "ChangeCurrentObj","linkMethod ...
	 * 		.id : GRPITEM[~^`grpItemId14`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Paquetes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Paquetes"), anchor, flags);
	}
	
	/**
	 * Personalizar: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"));
	}
	/**
	 * Personalizar: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"), anchor, flags);
	}
	
	/**
	 * PlanPaquete1000SMS: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 3
	 */
	protected ToggleGUITestObject PlanPaquete1000SMS() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete1000SMS"));
	}
	/**
	 * PlanPaquete1000SMS: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 3
	 */
	protected ToggleGUITestObject PlanPaquete1000SMS(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete1000SMS"), anchor, flags);
	}
	
	/**
	 * PlanPaquete100Min: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 4
	 */
	protected ToggleGUITestObject PlanPaquete100Min() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete100Min"));
	}
	/**
	 * PlanPaquete100Min: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 4
	 */
	protected ToggleGUITestObject PlanPaquete100Min(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete100Min"), anchor, flags);
	}
	
	/**
	 * PlanPaquete2000SMS: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 4
	 */
	protected ToggleGUITestObject PlanPaquete2000SMS() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete2000SMS"));
	}
	/**
	 * PlanPaquete2000SMS: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 4
	 */
	protected ToggleGUITestObject PlanPaquete2000SMS(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete2000SMS"), anchor, flags);
	}
	
	/**
	 * PlanPaquete30Min: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject PlanPaquete30Min() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete30Min"));
	}
	/**
	 * PlanPaquete30Min: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject PlanPaquete30Min(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete30Min"), anchor, flags);
	}
	
	/**
	 *  PlanPaquete500SMS: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject PlanPaquete500SMS() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete500SMS"));
	}
	/**
	 *  PlanPaquete500SMS: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject PlanPaquete500SMS(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete500SMS"), anchor, flags);
	}
	
	/**
	 * PlanPaquete50Min: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 3
	 */
	protected ToggleGUITestObject PlanPaquete50Min() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete50Min"));
	}
	/**
	 * PlanPaquete50Min: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 3
	 */
	protected ToggleGUITestObject PlanPaquete50Min(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquete50Min"), anchor, flags);
	}
	
	/**
	 * PlanPaquetePromMin : with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject PlanPaquetePromMin() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquetePromMin"));
	}
	/**
	 * PlanPaquetePromMin : with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA5Z.*DOMAIN)
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject PlanPaquetePromMin(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquetePromMin"), anchor, flags);
	}
	
	/**
	 * PlanPaquetePromSMS: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject PlanPaquetePromSMS() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquetePromSMS"));
	}
	/**
	 * PlanPaquetePromSMS: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM.*PORT.*1-SAYA61.*DOMAIN)
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject PlanPaquetePromSMS(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("PlanPaquetePromSMS"), anchor, flags);
	}
	
	/**
	 * PromocionesOpcionales: with default state.
	 *		.text : Promociones Opcionales
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId17", "ChangeCurrentObj","linkMethod ...
	 * 		.id : GRPITEM[~^`grpItemId17`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject PromocionesOpcionales() 
	{
		return new GuiTestObject(
                        getMappedTestObject("PromocionesOpcionales"));
	}
	/**
	 * PromocionesOpcionales: with specific test context and state.
	 *		.text : Promociones Opcionales
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId17", "ChangeCurrentObj","linkMethod ...
	 * 		.id : GRPITEM[~^`grpItemId17`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject PromocionesOpcionales(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("PromocionesOpcionales"), anchor, flags);
	}
	
	/**
	 * PromocionesyDescuentos: with default state.
	 *		.text : Promociones y Descuentos
	 * 		.href : javascript:processInput("GRPITEM[~^`1-S3ZW4A`^~[PORT[~^`1-S6QN1C`^~[PROD[~^`1-S6 ...
	 * 		.id : 1-S3ZW4A`^~[PORT[~^`1-S6QN1C`^~[PORTDOMAIN[~^`1-S6PR8B`^~[CXLINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject PromocionesyDescuentos() 
	{
		return new GuiTestObject(
                        getMappedTestObject("PromocionesyDescuentos"));
	}
	/**
	 * PromocionesyDescuentos: with specific test context and state.
	 *		.text : Promociones y Descuentos
	 * 		.href : javascript:processInput("GRPITEM[~^`1-S3ZW4A`^~[PORT[~^`1-S6QN1C`^~[PROD[~^`1-S6 ...
	 * 		.id : 1-S3ZW4A`^~[PORT[~^`1-S6QN1C`^~[PORTDOMAIN[~^`1-S6PR8B`^~[CXLINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject PromocionesyDescuentos(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("PromocionesyDescuentos"), anchor, flags);
	}
	
	/**
	 * Terminado: with default state.
	 *		.text : Terminado
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"DoneConfig","linkMethod"\) ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"));
	}
	/**
	 * Terminado: with specific test context and state.
	 *		.text : Terminado
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"DoneConfig","linkMethod"\) ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"), anchor, flags);
	}
	
	

	protected PersonalizarPromOpcHelper()
	{
		setScriptName("Scripts.Comun.PersonalizarPromOpc");
	}
	
}

