// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PersonalizarYCapturar</b><br>
 * Generated     : <b>2016/12/21 12:35:35</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 21, 2016
 * @author Sandra
 */
public abstract class PersonalizarYCapturarHelper extends libreria.Accion
{
	/**
	 * Personalizar: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject BtonPersonalizar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("BtonPersonalizar"));
	}
	/**
	 * Personalizar: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject BtonPersonalizar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("BtonPersonalizar"), anchor, flags);
	}
	
	/**
	 * Terminado: with default state.
	 *		.text : Terminado
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"DoneConfig","linkMethod"\) ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"));
	}
	/**
	 * Terminado: with specific test context and state.
	 *		.text : Terminado
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"DoneConfig","linkMethod"\) ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"), anchor, flags);
	}
	
	

	protected PersonalizarYCapturarHelper()
	{
		setScriptName("Scripts.Comun.PersonalizarYCapturar");
	}
	
}

