// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PersonalizarGrupoSVA</b><br>
 * Generated     : <b>2015/12/23 22:48:51</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 23, 2015
 * @author Sandra
 */
public abstract class PersonalizarGrupoSVAHelper extends libreria.Accion
{
	/**
	 * GRPITEM1RZ8NPBPORT1SNJ29ODOMAINon: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : GRPITEM[~^`1-RZ8NPB`^~[PORT[~^`1-SNJ29O`^~[DOMAIN
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject FavSMSOFF() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavSMSOFF"));
	}
	/**
	 * GRPITEM1RZ8NPBPORT1SNJ29ODOMAINon: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : GRPITEM[~^`1-RZ8NPB`^~[PORT[~^`1-SNJ29O`^~[DOMAIN
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject FavSMSOFF(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavSMSOFF"), anchor, flags);
	}
	
	/**
	 * GRPITEM1RZ8NPBPORT1SNJ29ODOMAINon: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : GRPITEM[~^`1-RZ8NPB`^~[PORT[~^`1-SNJ29O`^~[DOMAIN
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject FavSMSON() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavSMSON"));
	}
	/**
	 * GRPITEM1RZ8NPBPORT1SNJ29ODOMAINon: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : GRPITEM[~^`1-RZ8NPB`^~[PORT[~^`1-SNJ29O`^~[DOMAIN
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject FavSMSON(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavSMSON"), anchor, flags);
	}
	
	/**
	 * GRPITEM1RZ8NPBPORT1DYG0NEDOMAINon: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : GRPITEM[~^`1-RZ8NPB`^~[PORT[~^`1-DYG0NE`^~[DOMAIN
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject FavVozOFF() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavVozOFF"));
	}
	/**
	 * GRPITEM1RZ8NPBPORT1DYG0NEDOMAINon: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : GRPITEM[~^`1-RZ8NPB`^~[PORT[~^`1-DYG0NE`^~[DOMAIN
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject FavVozOFF(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavVozOFF"), anchor, flags);
	}
	
	/**
	 * GRPITEM1RZ8NPBPORT1DYG0NEDOMAINon: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM\[~\^`.*`\^~\[PORT\[~\^`1-DYG0NE`\^~\[DOMAIN)
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject FavVozON() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavVozON"));
	}
	/**
	 * GRPITEM1RZ8NPBPORT1DYG0NEDOMAINon: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : RegularExpression(GRPITEM\[~\^`.*`\^~\[PORT\[~\^`1-DYG0NE`\^~\[DOMAIN)
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject FavVozON(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("FavVozON"), anchor, flags);
	}
	
	/**
	 * _1RZFZT7PORT17WW69PORTDOMAIN16VIE6CXLINK: with default state.
	 *		.text : Grupo SVA
	 * 		.id : RegularExpression(\.\*`\^~\[PORT\[~\^`1-7WW69`\^~\[PORTDOMAIN\[~\^`1-6VIE6`\^~\[ ...
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM\[~\^`\.\*`\^~\[PORT\[~\^`1-7 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject GrupoSVA() 
	{
		return new GuiTestObject(
                        getMappedTestObject("GrupoSVA"));
	}
	/**
	 * _1RZFZT7PORT17WW69PORTDOMAIN16VIE6CXLINK: with specific test context and state.
	 *		.text : Grupo SVA
	 * 		.id : RegularExpression(\.\*`\^~\[PORT\[~\^`1-7WW69`\^~\[PORTDOMAIN\[~\^`1-6VIE6`\^~\[ ...
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM\[~\^`\.\*`\^~\[PORT\[~\^`1-7 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject GrupoSVA(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("GrupoSVA"), anchor, flags);
	}
	
	/**
	 * Arbol_lista: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * Arbol_lista: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * Breconfig: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"));
	}
	/**
	 * Breconfig: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"), anchor, flags);
	}
	
	/**
	 * GRPITEMGrpItemId13LINK: with default state.
	 *		.text : Servicios Adicionales
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId13", "ChangeCurrentObj","linkMethod ...
	 * 		.id : GRPITEM[~^`grpItemId13`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ServiciosAdicionales() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ServiciosAdicionales"));
	}
	/**
	 * GRPITEMGrpItemId13LINK: with specific test context and state.
	 *		.text : Servicios Adicionales
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId13", "ChangeCurrentObj","linkMethod ...
	 * 		.id : GRPITEM[~^`grpItemId13`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ServiciosAdicionales(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ServiciosAdicionales"), anchor, flags);
	}
	
	/**
	 * GRPITEMGrpItemId4LINK: with default state.
	 *		.text : Terminado
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId4", "DoneConfig","linkMethod")
	 * 		.id : GRPITEM[~^`grpItemId4`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"));
	}
	/**
	 * GRPITEMGrpItemId4LINK: with specific test context and state.
	 *		.text : Terminado
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId4", "DoneConfig","linkMethod")
	 * 		.id : GRPITEM[~^`grpItemId4`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"), anchor, flags);
	}
	
	

	protected PersonalizarGrupoSVAHelper()
	{
		setScriptName("Scripts.Comun.PersonalizarGrupoSVA");
	}
	
}

