// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Personalizar_SRV_MOV_PRE</b><br>
 * Generated     : <b>2016/12/21 12:34:51</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 21, 2016
 * @author Sandra
 */
public abstract class Personalizar_SRV_MOV_PREHelper extends libreria.Accion
{
	/**
	 * Advertencia: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject Advertencia() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Advertencia"));
	}
	/**
	 * Advertencia: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject Advertencia(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Advertencia"), anchor, flags);
	}
	
	/**
	 * ButtonOk: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ButtonOk
	 */
	protected SiebButtonTestObject ButtonOk() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("ButtonOk"));
	}
	/**
	 * ButtonOk: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ButtonOk
	 */
	protected SiebButtonTestObject ButtonOk(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("ButtonOk"), anchor, flags);
	}
	
	/**
	 * ErrorMessage: with default state.
	 *		ClassName : SiebTextArea
	 * 		.class : SiebTextArea
	 * 		RepositoryName : Error Message
	 */
	protected SiebTextAreaTestObject ErrorMessage() 
	{
		return new SiebTextAreaTestObject(
                        getMappedTestObject("ErrorMessage"));
	}
	/**
	 * ErrorMessage: with specific test context and state.
	 *		ClassName : SiebTextArea
	 * 		.class : SiebTextArea
	 * 		RepositoryName : Error Message
	 */
	protected SiebTextAreaTestObject ErrorMessage(TestObject anchor, long flags) 
	{
		return new SiebTextAreaTestObject(
                        getMappedTestObject("ErrorMessage"), anchor, flags);
	}
	
	/**
	 * Facilidades Telefonia Movil - Prepago: with default state.
	 *		.text : Facilidades Telefonia Movil
	 * 		.id : GRPITEM[~^`grpItemId12`^~[LINK
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId12", "ChangeCurrentObj","linkMethod ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Facilidades_Telefonia_Movil() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Facilidades_Telefonia_Movil"));
	}
	/**
	 * Facilidades Telefonia Movil - Prepago: with specific test context and state.
	 *		.text : Facilidades Telefonia Movil
	 * 		.id : GRPITEM[~^`grpItemId12`^~[LINK
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId12", "ChangeCurrentObj","linkMethod ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Facilidades_Telefonia_Movil(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Facilidades_Telefonia_Movil"), anchor, flags);
	}
	
	/**
	 * Finalicelo: with default state.
	 *		.text : Finalícelo
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"FinishIt","linkMethod"\))
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Finalicelo() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Finalicelo"));
	}
	/**
	 * Finalicelo: with specific test context and state.
	 *		.text : Finalícelo
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"FinishIt","linkMethod"\))
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Finalicelo(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Finalicelo"), anchor, flags);
	}
	
	/**
	 * Items_Facilidades_Telefonia_Movil: with default state.
	 *		.id : RegularExpression(.*PORT.*1-78LSK)
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Items_Facilidades_Telefonia_Movil() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Items_Facilidades_Telefonia_Movil"));
	}
	/**
	 * Items_Facilidades_Telefonia_Movil: with specific test context and state.
	 *		.id : RegularExpression(.*PORT.*1-78LSK)
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Items_Facilidades_Telefonia_Movil(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Items_Facilidades_Telefonia_Movil"), anchor, flags);
	}
	
	/**
	 * Personalizar: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"));
	}
	/**
	 * Personalizar: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"), anchor, flags);
	}
	
	/**
	 * PersonalizarPI: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject PersonalizarPI() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("PersonalizarPI"));
	}
	/**
	 * PersonalizarPI: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject PersonalizarPI(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("PersonalizarPI"), anchor, flags);
	}
	
	/**
	 * Terminado: with default state.
	 *		.text : Terminado
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"DoneConfig","linkMethod"\) ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminar"));
	}
	/**
	 * Terminado: with specific test context and state.
	 *		.text : Terminado
	 * 		.id : RegularExpression(GRPITEM.*LINK)
	 * 		.href : RegularExpression(javascript:processInput\("GRPITEM.*"DoneConfig","linkMethod"\) ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminar"), anchor, flags);
	}
	
	

	protected Personalizar_SRV_MOV_PREHelper()
	{
		setScriptName("Scripts.Comun.Personalizar_SRV_MOV_PRE");
	}
	
}

