// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SeleccionarTerminalPrepago</b><br>
 * Generated     : <b>2016/12/28 2:58:50 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 28, 2016
 * @author rft
 */
public abstract class SeleccionarTerminalPrepagoHelper extends libreria.Accion
{
	/**
	 * Personalizar: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"));
	}
	/**
	 * Personalizar: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : Breconfig
	 */
	protected SiebButtonTestObject Personalizar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Personalizar"), anchor, flags);
	}
	
	/**
	 * GRPITEMGrpItemId3LINK: with default state.
	 *		.text : Terminado
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId3", "DoneConfig","linkMethod")
	 * 		.id : GRPITEM[~^`grpItemId3`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"));
	}
	/**
	 * GRPITEMGrpItemId3LINK: with specific test context and state.
	 *		.text : Terminado
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId3", "DoneConfig","linkMethod")
	 * 		.id : GRPITEM[~^`grpItemId3`^~[LINK
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Terminado(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Terminado"), anchor, flags);
	}
	
	/**
	 * _1SU2OM3PORT1DHEG5: with default state.
	 *		.id : 1-SU2OM3`^~[PORT[~^`1-DHEG5
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Terminales() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Terminales"));
	}
	/**
	 * _1SU2OM3PORT1DHEG5: with specific test context and state.
	 *		.id : 1-SU2OM3`^~[PORT[~^`1-DHEG5
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject Terminales(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Terminales"), anchor, flags);
	}
	
	/**
	 * GRPITEMGrpItemId12LINK: with default state.
	 *		.text : Terminales Moviles
	 * 		.id : GRPITEM[~^`grpItemId12`^~[LINK
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId12", "ChangeCurrentObj","linkMethod ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject TerminalesMoviles() 
	{
		return new GuiTestObject(
                        getMappedTestObject("TerminalesMoviles"));
	}
	/**
	 * GRPITEMGrpItemId12LINK: with specific test context and state.
	 *		.text : Terminales Moviles
	 * 		.id : GRPITEM[~^`grpItemId12`^~[LINK
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId12", "ChangeCurrentObj","linkMethod ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject TerminalesMoviles(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("TerminalesMoviles"), anchor, flags);
	}
	
	/**
	 * _1SU36TDPORT1DHEG5: with default state.
	 *		.id : 1-SU36TD`^~[PORT[~^`1-DHEG5
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TerminalesPrepago() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TerminalesPrepago"));
	}
	/**
	 * _1SU36TDPORT1DHEG5: with specific test context and state.
	 *		.id : 1-SU36TD`^~[PORT[~^`1-DHEG5
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject TerminalesPrepago(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("TerminalesPrepago"), anchor, flags);
	}
	
	/**
	 * GRPITEMGrpItemId0LINK: with default state.
	 *		.text : Volver a valorar
	 * 		.id : GRPITEM[~^`grpItemId0`^~[LINK
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId0", "CalculatePriceCX","linkMethod" ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject VolveraValorar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("VolveraValorar"));
	}
	/**
	 * GRPITEMGrpItemId0LINK: with specific test context and state.
	 *		.text : Volver a valorar
	 * 		.id : GRPITEM[~^`grpItemId0`^~[LINK
	 * 		.href : javascript:processInput("GRPITEM[~^`grpItemId0", "CalculatePriceCX","linkMethod" ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject VolveraValorar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("VolveraValorar"), anchor, flags);
	}
	
	

	protected SeleccionarTerminalPrepagoHelper()
	{
		setScriptName("Scripts.Comun.SeleccionarTerminalPrepago");
	}
	
}

