// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SeleccionarPedidoCP</b><br>
 * Generated     : <b>2016/01/28 02:28:15</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 28, 2016
 * @author Sandra
 */
public abstract class SeleccionarPedidoCPHelper extends libreria.Accion
{
	/**
	 * Detalles: with default state.
	 *		.title : Detalles
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*\/ecommunications_esn/start\.swe\?SWECmdr.*)
	 */
	protected DocumentTestObject EncabezadoPedidoHTML() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("EncabezadoPedidoHTML"));
	}
	/**
	 * Detalles: with specific test context and state.
	 *		.title : Detalles
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http://.*\/ecommunications_esn/start\.swe\?SWECmdr.*)
	 */
	protected DocumentTestObject EncabezadoPedidoHTML(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("EncabezadoPedidoHTML"), anchor, flags);
	}
	
	/**
	 * OrderNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"));
	}
	/**
	 * OrderNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"), anchor, flags);
	}
	
	

	protected SeleccionarPedidoCPHelper()
	{
		setScriptName("Scripts.Comun.SeleccionarPedidoCP");
	}
	
}

