// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SetEnvioInfo</b><br>
 * Generated     : <b>2017/03/27 12:38:17</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  marzo 27, 2017
 * @author Sandra
 */
public abstract class SetEnvioInfoHelper extends libreria.Accion
{
	/**
	 * ICEEnvioInformacion: with default state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : ICE Envio Informacion
	 */
	protected SiebCheckboxTestObject EnvioInformacion() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("EnvioInformacion"));
	}
	/**
	 * ICEEnvioInformacion: with specific test context and state.
	 *		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		RepositoryName : ICE Envio Informacion
	 */
	protected SiebCheckboxTestObject EnvioInformacion(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("EnvioInformacion"), anchor, flags);
	}
	
	/**
	 * ToggleLayout: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ToggleLayout
	 */
	protected SiebButtonTestObject button_toggleLayout() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_toggleLayout"));
	}
	/**
	 * ToggleLayout: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ToggleLayout
	 */
	protected SiebButtonTestObject button_toggleLayout(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("button_toggleLayout"), anchor, flags);
	}
	
	/**
	 * MostrarMenos: with default state.
	 *		.alt : Mostrar menos
	 * 		.id : 
	 * 		.src : http://crmqa.intranet.ice/ecommunications_esn/images/btn_less.gif
	 * 		.title : Mostrar menos
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_mostrarMenos() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_mostrarMenos"));
	}
	/**
	 * MostrarMenos: with specific test context and state.
	 *		.alt : Mostrar menos
	 * 		.id : 
	 * 		.src : http://crmqa.intranet.ice/ecommunications_esn/images/btn_less.gif
	 * 		.title : Mostrar menos
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_mostrarMenos(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_mostrarMenos"), anchor, flags);
	}
	
	/**
	 * MostrarMás: with default state.
	 *		.alt : Mostrar más
	 * 		.id : 
	 * 		.src : http://crmqa.intranet.ice/ecommunications_esn/images/btn_more.gif
	 * 		.title : Mostrar más
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_mostrarMás() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_mostrarMás"));
	}
	/**
	 * MostrarMás: with specific test context and state.
	 *		.alt : Mostrar más
	 * 		.id : 
	 * 		.src : http://crmqa.intranet.ice/ecommunications_esn/images/btn_more.gif
	 * 		.title : Mostrar más
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_mostrarMás(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_mostrarMás"), anchor, flags);
	}
	
	

	protected SetEnvioInfoHelper()
	{
		setScriptName("Scripts.Comun.SetEnvioInfo");
	}
	
}

