// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarPrecio</b><br>
 * Generated     : <b>2017/03/31 12:10:14</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  marzo 31, 2017
 * @author Sandra
 */
public abstract class ValidarPrecioHelper extends libreria.Accion
{
	/**
	 * ItemPrice: with default state.
	 *		ClassName : SiebCurrency
	 * 		.class : SiebCurrency
	 * 		RepositoryName : Item Price
	 */
	protected SiebCurrencyTestObject PrecioNeto() 
	{
		return new SiebCurrencyTestObject(
                        getMappedTestObject("PrecioNeto"));
	}
	/**
	 * ItemPrice: with specific test context and state.
	 *		ClassName : SiebCurrency
	 * 		.class : SiebCurrency
	 * 		RepositoryName : Item Price
	 */
	protected SiebCurrencyTestObject PrecioNeto(TestObject anchor, long flags) 
	{
		return new SiebCurrencyTestObject(
                        getMappedTestObject("PrecioNeto"), anchor, flags);
	}
	
	/**
	 * ItemPrice: with default state.
	 *		ClassName : SiebCurrency
	 * 		.class : SiebCurrency
	 * 		RepositoryName : Item Price
	 */
	protected SiebCurrencyTestObject PrecioNetoPI() 
	{
		return new SiebCurrencyTestObject(
                        getMappedTestObject("PrecioNetoPI"));
	}
	/**
	 * ItemPrice: with specific test context and state.
	 *		ClassName : SiebCurrency
	 * 		.class : SiebCurrency
	 * 		RepositoryName : Item Price
	 */
	protected SiebCurrencyTestObject PrecioNetoPI(TestObject anchor, long flags) 
	{
		return new SiebCurrencyTestObject(
                        getMappedTestObject("PrecioNetoPI"), anchor, flags);
	}
	
	

	protected ValidarPrecioHelper()
	{
		setScriptName("Scripts.Comun.ValidarPrecio");
	}
	
}

