// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidacPostEnvio2</b><br>
 * Generated     : <b>2016/03/30 08:39:07</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  marzo 30, 2016
 * @author Sandra
 */
public abstract class ValidacPostEnvio2Helper extends libreria.Accion
{
	/**
	 * EstadoPedido: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Status
	 */
	protected SiebPicklistTestObject EstadoPedidoVta() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoPedidoVta"));
	}
	/**
	 * EstadoPedido: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Status
	 */
	protected SiebPicklistTestObject EstadoPedidoVta(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("EstadoPedidoVta"), anchor, flags);
	}
	
	/**
	 * IMSI: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMSI
	 */
	protected SiebTextTestObject IMSI() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMSI"));
	}
	/**
	 * IMSI: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMSI
	 */
	protected SiebTextTestObject IMSI(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMSI"), anchor, flags);
	}
	
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	/**
	 * Tecnologia: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE SIM Tech
	 */
	protected SiebTextTestObject Tecnologia() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Tecnologia"));
	}
	/**
	 * Tecnologia: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE SIM Tech
	 */
	protected SiebTextTestObject Tecnologia(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Tecnologia"), anchor, flags);
	}
	
	/**
	 * BupdatePriceAll: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject VolveraValorar() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("VolveraValorar"));
	}
	/**
	 * BupdatePriceAll: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject VolveraValorar(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("VolveraValorar"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point SiebList_selectedText object in the SUT.
	 */
	protected IFtVerificationPoint SiebList_selectedTextVP() 
	{
		return vp("SiebList_selectedText");
	}
	protected IFtVerificationPoint SiebList_selectedTextVP(TestObject anchor)
	{
		return vp("SiebList_selectedText", anchor);
	}
	
	

	protected ValidacPostEnvio2Helper()
	{
		setScriptName("Scripts.Comun.ValidacPostEnvio2");
	}
	
}

