// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarCamposTerminalCM_Ant</b><br>
 * Generated     : <b>2017/03/22 10:31:31</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  marzo 22, 2017
 * @author Sandra
 */
public abstract class ValidarCamposTerminalCM_AntHelper extends libreria.Accion
{
	/**
	 * ICEMarca: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Marca
	 */
	protected SiebTextTestObject Marca() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Marca"));
	}
	/**
	 * ICEMarca: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Marca
	 */
	protected SiebTextTestObject Marca(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Marca"), anchor, flags);
	}
	
	/**
	 * ICEModelo: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Modelo
	 */
	protected SiebTextTestObject Modelo() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Modelo"));
	}
	/**
	 * ICEModelo: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Modelo
	 */
	protected SiebTextTestObject Modelo(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Modelo"), anchor, flags);
	}
	
	/**
	 * ICENumeroSerie: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Numero Serie
	 */
	protected SiebTextTestObject Serie() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Serie"));
	}
	/**
	 * ICENumeroSerie: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Numero Serie
	 */
	protected SiebTextTestObject Serie(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Serie"), anchor, flags);
	}
	
	/**
	 * ICEVersionSoft: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Version Soft
	 */
	protected SiebTextTestObject Version() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Version"));
	}
	/**
	 * ICEVersionSoft: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Version Soft
	 */
	protected SiebTextTestObject Version(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Version"), anchor, flags);
	}
	
	

	protected ValidarCamposTerminalCM_AntHelper()
	{
		setScriptName("Scripts.Comun.ValidarCamposTerminalCM_Ant");
	}
	
}

