// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarIMEICP</b><br>
 * Generated     : <b>2016/06/06 13:51:23</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  junio 06, 2016
 * @author Sandra
 */
public abstract class ValidarIMEICPHelper extends libreria.Accion
{
	/**
	 * ICETerminalCliente: with default state.
	 *		IsChecked : false
	 * 		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		IsEnabled : true
	 * 		RepositoryName : ICE Terminal Cliente
	 */
	protected SiebCheckboxTestObject CheckTerminalCliente() 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("CheckTerminalCliente"));
	}
	/**
	 * ICETerminalCliente: with specific test context and state.
	 *		IsChecked : false
	 * 		ClassName : SiebCheckbox
	 * 		.class : SiebCheckbox
	 * 		IsEnabled : true
	 * 		RepositoryName : ICE Terminal Cliente
	 */
	protected SiebCheckboxTestObject CheckTerminalCliente(TestObject anchor, long flags) 
	{
		return new SiebCheckboxTestObject(
                        getMappedTestObject("CheckTerminalCliente"), anchor, flags);
	}
	
	/**
	 * IMEI: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMEI
	 */
	protected SiebTextTestObject IMEI() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMEI"));
	}
	/**
	 * IMEI: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE IMEI
	 */
	protected SiebTextTestObject IMEI(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("IMEI"), anchor, flags);
	}
	
	/**
	 * LineasPedido: with default state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"));
	}
	/**
	 * LineasPedido: with specific test context and state.
	 *		ActiveRow : 9
	 * 		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 * 		SelectedRows : 9
	 */
	protected SiebListTestObject LineasPedido(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("LineasPedido"), anchor, flags);
	}
	
	

	protected ValidarIMEICPHelper()
	{
		setScriptName("Scripts.Comun.ValidarIMEICP");
	}
	
}

