// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarMensaje</b><br>
 * Generated     : <b>2015/12/18 11:56:04</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 18, 2015
 * @author Sandra
 */
public abstract class ValidarMensajeHelper extends libreria.Accion
{
	/**
	 * AceptarMensajeHTMLSiebel: with default state.
	 *		.text : RegularExpression((Aceptar|OK))
	 * 		.class : Html.DialogButton
	 * 		.disabled : false
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensaje() 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensaje"));
	}
	/**
	 * AceptarMensajeHTMLSiebel: with specific test context and state.
	 *		.text : RegularExpression((Aceptar|OK))
	 * 		.class : Html.DialogButton
	 * 		.disabled : false
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensaje(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensaje"), anchor, flags);
	}
	
	/**
	 * HtmlDialogButtonAceptar: with default state.
	 *		.text : Aceptar
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensajeBrowser() 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensajeBrowser"));
	}
	/**
	 * HtmlDialogButtonAceptar: with specific test context and state.
	 *		.text : Aceptar
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensajeBrowser(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensajeBrowser"), anchor, flags);
	}
	
	/**
	 * HtmlDialogStaticAsegureseDeOfrecerFavoritoVOZYaQueSeEnc: with default state.
	 *		.text : RegularExpression(.*)
	 * 		.class : Html.DialogStatic
	 * 		.classIndex : 1
	 */
	protected GuiTestObject MensajeBrowserScript() 
	{
		return new GuiTestObject(
                        getMappedTestObject("MensajeBrowserScript"));
	}
	/**
	 * HtmlDialogStaticAsegureseDeOfrecerFavoritoVOZYaQueSeEnc: with specific test context and state.
	 *		.text : RegularExpression(.*)
	 * 		.class : Html.DialogStatic
	 * 		.classIndex : 1
	 */
	protected GuiTestObject MensajeBrowserScript(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("MensajeBrowserScript"), anchor, flags);
	}
	
	/**
	 * MensajeErrorHTMLSiebel: with default state.
	 *		.text : RegularExpression(.*SBL.*)
	 * 		.class : Html.DialogStatic
	 * 		.disabled : false
	 * 		.classIndex : 1
	 */
	protected GuiTestObject MensajeJavaError() 
	{
		return new GuiTestObject(
                        getMappedTestObject("MensajeJavaError"));
	}
	/**
	 * MensajeErrorHTMLSiebel: with specific test context and state.
	 *		.text : RegularExpression(.*SBL.*)
	 * 		.class : Html.DialogStatic
	 * 		.disabled : false
	 * 		.classIndex : 1
	 */
	protected GuiTestObject MensajeJavaError(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("MensajeJavaError"), anchor, flags);
	}
	
	

	protected ValidarMensajeHelper()
	{
		setScriptName("Scripts.Comun.ValidarMensaje");
	}
	
}

