// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidaMulta</b><br>
 * Generated     : <b>2016/07/04 13:13:37</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  julio 04, 2016
 * @author Sandra
 */
public abstract class ValidaMultaHelper extends libreria.Accion
{
	/**
	 * BrowserIE: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.documentName : RegularExpression(http.*\/ecommunications_esn/start\.swe.*)
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject BrowserIE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("BrowserIE"));
	}
	/**
	 * BrowserIE: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.documentName : RegularExpression(http.*\/ecommunications_esn/start\.swe.*)
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject BrowserIE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("BrowserIE"), anchor, flags);
	}
	
	/**
	 * BtonVerMulta: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEPenaltyURL
	 */
	protected SiebButtonTestObject BtonVerMulta() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("BtonVerMulta"));
	}
	/**
	 * BtonVerMulta: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEPenaltyURL
	 */
	protected SiebButtonTestObject BtonVerMulta(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("BtonVerMulta"), anchor, flags);
	}
	
	/**
	 * ChkTodosPlanes: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : S
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : ChkTodosPlanes
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject ChkTodosPlanes() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("ChkTodosPlanes"));
	}
	/**
	 * ChkTodosPlanes: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : S
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : ChkTodosPlanes
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject ChkTodosPlanes(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("ChkTodosPlanes"), anchor, flags);
	}
	
	/**
	 * ConsultaMultasxCP: with default state.
	 *		.title : Consulta de Posibles Multas por Cambio de Plan
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://cer.infocom.ice/atvpub/ATV/interfaz/ATV_CambioPlan.jsp
	 */
	protected DocumentTestObject ConsultaMultasxCP() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("ConsultaMultasxCP"));
	}
	/**
	 * ConsultaMultasxCP: with specific test context and state.
	 *		.title : Consulta de Posibles Multas por Cambio de Plan
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://cer.infocom.ice/atvpub/ATV/interfaz/ATV_CambioPlan.jsp
	 */
	protected DocumentTestObject ConsultaMultasxCP(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("ConsultaMultasxCP"), anchor, flags);
	}
	
	/**
	 * MultasxPlan: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject MultasxPlan() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("MultasxPlan"));
	}
	/**
	 * MultasxPlan: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject MultasxPlan(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("MultasxPlan"), anchor, flags);
	}
	
	/**
	 * ResumenMultas: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject ResumenMultas() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("ResumenMultas"));
	}
	/**
	 * ResumenMultas: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject ResumenMultas(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("ResumenMultas"), anchor, flags);
	}
	
	

	protected ValidaMultaHelper()
	{
		setScriptName("Scripts.Comun.ValidaMulta");
	}
	
}

