// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarAtributosPedido</b><br>
 * Generated     : <b>2016/12/21 12:38:50</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 21, 2016
 * @author Sandra
 */
public abstract class ValidarAtributosPedidoHelper extends libreria.Accion
{
	/**
	 * HtmlTable_3: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 3
	 */
	protected StatelessGuiSubitemTestObject Atributos() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Atributos"));
	}
	/**
	 * HtmlTable_3: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 3
	 */
	protected StatelessGuiSubitemTestObject Atributos(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("Atributos"), anchor, flags);
	}
	
	/**
	 * BtonConsultaPedido: with default state.
	 *		.text : Consulta
	 * 		.href : javascript:void(0)
	 * 		.id : s_1_1_151_0_mb
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultaPedido() 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultaPedido"));
	}
	/**
	 * BtonConsultaPedido: with specific test context and state.
	 *		.text : Consulta
	 * 		.href : javascript:void(0)
	 * 		.id : s_1_1_151_0_mb
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject BtonConsultaPedido(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("BtonConsultaPedido"), anchor, flags);
	}
	
	/**
	 * ListaAtributos: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaAtributos() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaAtributos"));
	}
	/**
	 * ListaAtributos: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaAtributos(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaAtributos"), anchor, flags);
	}
	
	/**
	 * Nombre: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Display Name
	 */
	protected SiebTextTestObject Nombre() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Nombre"));
	}
	/**
	 * Nombre: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Display Name
	 */
	protected SiebTextTestObject Nombre(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("Nombre"), anchor, flags);
	}
	
	/**
	 * TabsPedidoVta: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject TabsPedidoVta() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("TabsPedidoVta"));
	}
	/**
	 * TabsPedidoVta: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject TabsPedidoVta(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("TabsPedidoVta"), anchor, flags);
	}
	
	/**
	 * Valor: with default state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Value
	 */
	protected SiebPicklistTestObject Valor() 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("Valor"));
	}
	/**
	 * Valor: with specific test context and state.
	 *		ClassName : SiebPicklist
	 * 		.class : SiebPicklist
	 * 		RepositoryName : Value
	 */
	protected SiebPicklistTestObject Valor(TestObject anchor, long flags) 
	{
		return new SiebPicklistTestObject(
                        getMappedTestObject("Valor"), anchor, flags);
	}
	
	

	protected ValidarAtributosPedidoHelper()
	{
		setScriptName("Scripts.Comun.ValidarAtributosPedido");
	}
	
}

