// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarBtnAnularRED</b><br>
 * Generated     : <b>2017/04/07 12:49:36 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 07, 2017
 * @author rft
 */
public abstract class ValidarBtnAnularREDHelper extends libreria.Accion
{
	/**
	 * AnularRED: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEAnularRED
	 */
	protected SiebButtonTestObject AnularRED() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("AnularRED"));
	}
	/**
	 * AnularRED: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEAnularRED
	 */
	protected SiebButtonTestObject AnularRED(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("AnularRED"), anchor, flags);
	}
	
	/**
	 * AnularREDPI: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEAnularRED
	 */
	protected SiebButtonTestObject AnularRED_PI() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("AnularRED_PI"));
	}
	/**
	 * AnularREDPI: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ICEAnularRED
	 */
	protected SiebButtonTestObject AnularRED_PI(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("AnularRED_PI"), anchor, flags);
	}
	
	

	protected ValidarBtnAnularREDHelper()
	{
		setScriptName("Scripts.Comun.ValidarBtnAnularRED");
	}
	
}

