// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarActivoenCtaFact_TipoPed</b><br>
 * Generated     : <b>2017/04/25 8:22:00 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 25, 2017
 * @author rft
 */
public abstract class ValidarActivoenCtaFact_TipoPedHelper extends libreria.Accion
{
	/**
	 * ExecuteQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject EjecConsulta() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("EjecConsulta"));
	}
	/**
	 * ExecuteQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject EjecConsulta(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("EjecConsulta"), anchor, flags);
	}
	
	/**
	 * NewQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NuevaConsulta() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaConsulta"));
	}
	/**
	 * NewQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NuevaConsulta(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaConsulta"), anchor, flags);
	}
	
	/**
	 * ICECalculatedOrderType: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Calculated Order Type
	 */
	protected SiebTextTestObject TipoPedido() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("TipoPedido"));
	}
	/**
	 * ICECalculatedOrderType: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : ICE Calculated Order Type
	 */
	protected SiebTextTestObject TipoPedido(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("TipoPedido"), anchor, flags);
	}
	
	/**
	 * NroPedido: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Order Number
	 */
	protected SiebTextTestObject nroPedido() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("nroPedido"));
	}
	/**
	 * NroPedido: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : Order Number
	 */
	protected SiebTextTestObject nroPedido(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("nroPedido"), anchor, flags);
	}
	
	

	protected ValidarActivoenCtaFact_TipoPedHelper()
	{
		setScriptName("Scripts.Comun.ValidarActivoenCtaFact_TipoPed");
	}
	
}

