// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarCacheSiebel</b><br>
 * Generated     : <b>2016/12/21 12:39:08</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  diciembre 21, 2016
 * @author Sandra
 */
public abstract class ValidarCacheSiebelHelper extends libreria.Accion
{
	/**
	 * _swecache: with default state.
	 *		.id : _swecache
	 * 		.title : 
	 * 		.class : Html.FRAMESET
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Cache() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Cache"));
	}
	/**
	 * _swecache: with specific test context and state.
	 *		.id : _swecache
	 * 		.title : 
	 * 		.class : Html.FRAMESET
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Cache(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Cache"), anchor, flags);
	}
	
	

	protected ValidarCacheSiebelHelper()
	{
		setScriptName("Scripts.Comun.ValidarCacheSiebel");
	}
	
}

