// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValidarBtonValorarTodo</b><br>
 * Generated     : <b>2016/04/06 16:58:45</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  abril 06, 2016
 * @author Sandra
 */
public abstract class ValidarBtonValorarTodoHelper extends libreria.Accion
{
	/**
	 * Valorar_Todo: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject Valorar_Todo() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Valorar_Todo"));
	}
	/**
	 * Valorar_Todo: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject Valorar_Todo(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Valorar_Todo"), anchor, flags);
	}
	
	/**
	 * Valorar_Todo_PI: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject Valorar_Todo_PI() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Valorar_Todo_PI"));
	}
	/**
	 * Valorar_Todo_PI: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject Valorar_Todo_PI(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Valorar_Todo_PI"), anchor, flags);
	}
	
	

	protected ValidarBtonValorarTodoHelper()
	{
		setScriptName("Scripts.Comun.ValidarBtonValorarTodo");
	}
	
}

