// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ValorarTodo</b><br>
 * Generated     : <b>2016/01/11 19:22:35</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 11, 2016
 * @author Sandra
 */
public abstract class ValorarTodoHelper extends libreria.Accion
{
	/**
	 * AceptarMensajeBrowser: with default state.
	 *		.text : Aceptar
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensajeBrowser() 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensajeBrowser"));
	}
	/**
	 * AceptarMensajeBrowser: with specific test context and state.
	 *		.text : Aceptar
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject AceptarMensajeBrowser(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("AceptarMensajeBrowser"), anchor, flags);
	}
	
	/**
	 * MensajeBrowserScript: with default state.
	 *		.text : RegularExpression(.*)
	 * 		.class : Html.DialogStatic
	 * 		.classIndex : 1
	 */
	protected GuiTestObject MensajeBrowserScript() 
	{
		return new GuiTestObject(
                        getMappedTestObject("MensajeBrowserScript"));
	}
	/**
	 * MensajeBrowserScript: with specific test context and state.
	 *		.text : RegularExpression(.*)
	 * 		.class : Html.DialogStatic
	 * 		.classIndex : 1
	 */
	protected GuiTestObject MensajeBrowserScript(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("MensajeBrowserScript"), anchor, flags);
	}
	
	/**
	 * BupdatePriceAll: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject Valorar_Todo() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Valorar_Todo"));
	}
	/**
	 * BupdatePriceAll: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : BupdatePriceAll
	 */
	protected SiebButtonTestObject Valorar_Todo(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("Valorar_Todo"), anchor, flags);
	}
	
	

	protected ValorarTodoHelper()
	{
		setScriptName("Scripts.Comun.ValorarTodo");
	}
	
}

