// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Scripts.Comun;
import libreria.Accion;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Vista360</b><br>
 * Generated     : <b>2016/01/25 16:44:52</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  enero 25, 2016
 * @author Sandra
 */
public abstract class Vista360Helper extends libreria.Accion
{
	/**
	 * ExecuteQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject EjecutarQuery() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("EjecutarQuery"));
	}
	/**
	 * ExecuteQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : ExecuteQuery
	 */
	protected SiebButtonTestObject EjecutarQuery(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("EjecutarQuery"), anchor, flags);
	}
	
	/**
	 * Ir: with default state.
	 *		.text : Ir
	 * 		.id : s_1_1_13_0
	 * 		.href : javascript:void(0)
	 * 		OT : SiebWebButton
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Account Home Search Virtual Form Applet.MirrorSearchGotoView
	 * 		UN : Ir
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Ir() 
	{
		return new GuiTestObject(
                        getMappedTestObject("Ir"));
	}
	/**
	 * Ir: with specific test context and state.
	 *		.text : Ir
	 * 		.id : s_1_1_13_0
	 * 		.href : javascript:void(0)
	 * 		OT : SiebWebButton
	 * 		.title : 
	 * 		.class : Html.A
	 * 		RN : Account Home Search Virtual Form Applet.MirrorSearchGotoView
	 * 		UN : Ir
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject Ir(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("Ir"), anchor, flags);
	}
	
	/**
	 * SiebList: with default state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaCuentas() 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaCuentas"));
	}
	/**
	 * SiebList: with specific test context and state.
	 *		ClassName : SiebList
	 * 		.class : SiebList
	 * 		RepositoryName : SiebList
	 */
	protected SiebListTestObject ListaCuentas(TestObject anchor, long flags) 
	{
		return new SiebListTestObject(
                        getMappedTestObject("ListaCuentas"), anchor, flags);
	}
	
	/**
	 * LogoOracle: with default state.
	 *		.alt : Con tecnología Siebel
	 * 		.id : 
	 * 		.src : RegularExpression(http://.*\/ecommunications_esn/images/ebus\.gif)
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject LogoOracle() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("LogoOracle"));
	}
	/**
	 * LogoOracle: with specific test context and state.
	 *		.alt : Con tecnología Siebel
	 * 		.id : 
	 * 		.src : RegularExpression(http://.*\/ecommunications_esn/images/ebus\.gif)
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject LogoOracle(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("LogoOracle"), anchor, flags);
	}
	
	/**
	 * NºDeCuenta: with default state.
	 *		.id : s_1_1_3_0
	 * 		.type : text
	 * 		OT : SiebWebText
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		RN : Account Home Search Virtual Form Applet.Account Number
	 * 		UN : Nº de cuenta
	 * 		.name : s_1_1_3_0
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject NroCuenta() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("NroCuenta"));
	}
	/**
	 * NºDeCuenta: with specific test context and state.
	 *		.id : s_1_1_3_0
	 * 		.type : text
	 * 		OT : SiebWebText
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		RN : Account Home Search Virtual Form Applet.Account Number
	 * 		UN : Nº de cuenta
	 * 		.name : s_1_1_3_0
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject NroCuenta(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("NroCuenta"), anchor, flags);
	}
	
	/**
	 * OrderNumber: with default state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido() 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"));
	}
	/**
	 * OrderNumber: with specific test context and state.
	 *		ClassName : SiebText
	 * 		.class : SiebText
	 * 		RepositoryName : OrderNumber
	 */
	protected SiebTextTestObject NroPedido(TestObject anchor, long flags) 
	{
		return new SiebTextTestObject(
                        getMappedTestObject("NroPedido"), anchor, flags);
	}
	
	/**
	 * NewQuery: with default state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NuevaConsuta() 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaConsuta"));
	}
	/**
	 * NewQuery: with specific test context and state.
	 *		ClassName : SiebButton
	 * 		.class : SiebButton
	 * 		RepositoryName : NewQuery
	 */
	protected SiebButtonTestObject NuevaConsuta(TestObject anchor, long flags) 
	{
		return new SiebButtonTestObject(
                        getMappedTestObject("NuevaConsuta"), anchor, flags);
	}
	
	/**
	 * Pestañas: with default state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject Pestañas() 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("Pestañas"));
	}
	/**
	 * Pestañas: with specific test context and state.
	 *		ClassName : SiebPageTabs
	 * 		.class : SiebPageTabs
	 * 		RepositoryName : SiebPageTabs
	 */
	protected SiebPageTabsTestObject Pestañas(TestObject anchor, long flags) 
	{
		return new SiebPageTabsTestObject(
                        getMappedTestObject("Pestañas"), anchor, flags);
	}
	
	/**
	 * SiebScreenViews: with default state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject SiebScreenViews() 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("SiebScreenViews"));
	}
	/**
	 * SiebScreenViews: with specific test context and state.
	 *		ClassName : SiebScreenViews
	 * 		.class : SiebScreenViews
	 * 		RepositoryName : SiebScreenViews
	 */
	protected SiebScreenViewsTestObject SiebScreenViews(TestObject anchor, long flags) 
	{
		return new SiebScreenViewsTestObject(
                        getMappedTestObject("SiebScreenViews"), anchor, flags);
	}
	
	

	protected Vista360Helper()
	{
		setScriptName("Scripts.Comun.Vista360");
	}
	
}

